package v1

import (
	"net/http"
	"time"

	"github.com/evrone/go-clean-template/internal/controller/restapi/middleware"
	"github.com/gofiber/fiber/v2"
)

func (r *V1) registerGripStoreRoutes(apiV1Group fiber.Router) {
	authGroup := apiV1Group.Group("/auth")
	authGroup.Post("/refresh", r.gripRefresh)
	authGroup.Post("/logout", middleware.Auth(r.jwtManager), r.gripLogout)
	authGroup.Get("/me", middleware.Auth(r.jwtManager), r.gripMe)

	catalogGroup := apiV1Group.Group("/catalog")
	catalogGroup.Get("/products", r.gripListProducts)
	catalogGroup.Get("/products/:id", r.gripGetProduct)
	catalogGroup.Get("/products/:id/buy-meta", r.gripGetBuyMeta)
	catalogGroup.Get("/products/:id/reviews", r.gripReviewList)
	catalogGroup.Get("/search", r.gripSearchProducts)
	catalogGroup.Get("/categories", r.gripListCategories)
	catalogGroup.Get("/settings", r.gripListSettings)
	catalogGroup.Get("/announcement", r.gripGetAnnouncement)
	apiV1Group.Get("/site-config", r.gripSiteConfig)

	checkoutGroup := apiV1Group.Group("/checkout", middleware.RateLimitByIP(30, time.Minute))
	checkoutGroup.Get("/preview", r.gripCheckoutPreview)
	checkoutGroup.Post("/orders", middleware.Auth(r.jwtManager), r.gripCreateOrder)
	checkoutGroup.Post("/payment-orders", middleware.Auth(r.jwtManager), r.gripCreatePaymentOrder)
	checkoutGroup.Get("/orders/:id/payment-params", r.gripPaymentParams)
	checkoutGroup.Get("/orders/:id/status", middleware.Auth(r.jwtManager), r.gripOrderStatus)
	checkoutGroup.Post("/orders/:id/cancel", middleware.Auth(r.jwtManager), r.gripCancelOrder)
	checkoutGroup.Post("/notify", r.gripPaymentNotify)
	checkoutGroup.Get("/callback/:id", r.gripPaymentCallback)

	ordersGroup := apiV1Group.Group("/orders", middleware.Auth(r.jwtManager))
	ordersGroup.Get("/", r.gripListOrders)
	ordersGroup.Get("/:id", r.gripGetOrder)
	ordersGroup.Post("/:id/refund-request", r.gripRequestRefund)

	profileGroup := apiV1Group.Group("/profile", middleware.Auth(r.jwtManager))
	profileGroup.Get("/", r.gripProfileGet)
	profileGroup.Patch("/", r.gripProfileUpdate)
	profileGroup.Post("/check-in", r.gripProfileCheckin)

	wishlistGroup := apiV1Group.Group("/wishlist")
	wishlistGroup.Get("/", r.gripWishlistList)
	wishlistGroup.Post("/", middleware.Auth(r.jwtManager), r.gripWishlistCreate)
	wishlistGroup.Patch("/:id", middleware.Auth(r.jwtManager), r.gripWishlistUpdate)
	wishlistGroup.Delete("/:id", middleware.Auth(r.jwtManager), r.gripWishlistDelete)
	wishlistGroup.Post("/:id/vote", middleware.Auth(r.jwtManager), r.gripWishlistVote)

	apiV1Group.Get("/reviews", r.gripReviewList)
	apiV1Group.Get("/products/:id/reviews", r.gripReviewList)
	apiV1Group.Post("/products/:id/reviews", middleware.Auth(r.jwtManager), r.gripReviewCreate)
	apiV1Group.Get("/faqs/active", r.listActiveFAQs)

	reviewsGroup := apiV1Group.Group("/reviews", middleware.Auth(r.jwtManager))
	reviewsGroup.Post("/", r.gripReviewCreate)

	notificationGroup := apiV1Group.Group("/notifications", middleware.Auth(r.jwtManager))
	notificationGroup.Get("/", r.gripNotificationsList)
	notificationGroup.Get("/unread-count", r.gripNotificationsUnread)
	notificationGroup.Post("/:id/read", r.gripNotificationsMarkRead)
	notificationGroup.Post("/read-all", r.gripNotificationsReadAll)
	notificationGroup.Delete("/", r.gripNotificationsClear)

	adminGroup := apiV1Group.Group("/admin", middleware.Auth(r.jwtManager), middleware.RequireAdminUsernames(r.adminUsers))
	adminGroup.Get("/products", r.gripAdminListProducts)
	adminGroup.Post("/products", r.gripAdminCreateProduct)
	adminGroup.Patch("/products/:id", r.gripAdminUpdateProduct)
	adminGroup.Delete("/products/:id", r.gripAdminDeleteProduct)
	adminGroup.Get("/categories", r.gripAdminListCategories)
	adminGroup.Post("/categories", r.gripAdminCreateCategory)
	adminGroup.Patch("/categories/:id", r.gripAdminUpdateCategory)
	adminGroup.Delete("/categories/:id", r.gripAdminDeleteCategory)
	adminGroup.Get("/cards", r.gripAdminListCards)
	adminGroup.Post("/cards", r.gripAdminCreateCard)
	adminGroup.Delete("/cards/:id", r.gripAdminDeleteCard)
	adminGroup.Post("/cards/import", r.gripAdminCardsImport)
	adminGroup.Post("/cards/replenish", r.gripAdminCardsReplenish)
	adminGroup.Get("/orders", r.gripAdminListOrders)
	adminGroup.Get("/orders/:id", r.gripAdminGetOrder)
	adminGroup.Patch("/orders/:id", r.gripAdminUpdateOrder)
	adminGroup.Delete("/orders/:id", r.gripAdminDeleteOrder)
	adminGroup.Get("/refunds", r.gripAdminListRefunds)
	adminGroup.Post("/refunds/:id/approve", r.gripAdminApproveRefund)
	adminGroup.Post("/refunds/:id/reject", r.gripAdminRejectRefund)
	adminGroup.Get("/users", r.gripAdminUsersList)
	adminGroup.Patch("/users/:id", r.gripAdminUsersUpdate)
	adminGroup.Get("/reviews", r.gripAdminListReviews)
	adminGroup.Put("/reviews/:id/approve", r.gripAdminApproveReview)
	adminGroup.Put("/reviews/:id/hide", r.gripAdminHideReview)
	adminGroup.Put("/reviews/:id/feature", r.gripAdminFeatureReview)
	adminGroup.Post("/reviews/publish-selected", r.gripAdminPublishSelectedReviews)
	adminGroup.Delete("/reviews/:id", r.gripAdminDeleteReview)
	adminGroup.Get("/settings", r.gripAdminListSettings)
	adminGroup.Put("/settings/:key", r.gripAdminUpsertSetting)
	adminGroup.Delete("/settings/:key", r.gripAdminDeleteSetting)
	adminGroup.Get("/store-settings", r.gripAdminGetStoreSettings)
	adminGroup.Put("/store-settings/brand", r.gripAdminPutStoreSettingsBrand)
	adminGroup.Put("/store-settings/contact", r.gripAdminPutStoreSettingsContact)
	adminGroup.Put("/store-settings/homepage", r.gripAdminPutStoreSettingsHomepage)
	adminGroup.Put("/store-settings/footer", r.gripAdminPutStoreSettingsFooter)
	adminGroup.Put("/store-settings/floating-support", r.gripAdminPutStoreSettingsFloatingSupport)
	adminGroup.Put("/store-settings/visibility", r.gripAdminPutStoreSettingsVisibility)
	adminGroup.Put("/store-settings/registry", r.gripAdminPutStoreSettingsRegistry)
	adminGroup.Post("/messages/broadcast", r.gripAdminBroadcast)
	adminGroup.Post("/messages/targeted", r.gripAdminTargeted)
	adminGroup.Post("/notifications/test", r.gripAdminNotificationTest)
	adminGroup.Post("/data/import", r.gripAdminImportData)
	adminGroup.Post("/data/repair-aggregates", r.gripAdminRepairAggregates)
	adminGroup.Get("/media/presigned", r.getPresignedURL)
	adminGroup.Get("/media", r.listMedia)
	adminGroup.Post("/media", r.createMedia)
	adminGroup.Delete("/media/:id", r.deleteMedia)
	adminGroup.Get("/banners", r.listAdminBanners)
	adminGroup.Post("/banners", r.saveAdminBanner)
	adminGroup.Delete("/banners/:id", r.deleteAdminBanner)
	adminGroup.Get("/faqs", r.listAdminFAQs)
	adminGroup.Post("/faqs", r.saveAdminFAQ)
	adminGroup.Delete("/faqs/:id", r.deleteAdminFAQ)
	adminGroup.Get("/products/new", r.gripAdminProductsNew)
	adminGroup.Get("/products/:id/form", r.gripAdminProductForm)
}

func (r *V1) notImplemented(ctx *fiber.Ctx) error {
	return ctx.Status(http.StatusNotImplemented).JSON(fiber.Map{
		"error": "not_implemented",
	})
}
