// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repo/contracts.go
//
// Generated by this command:
//
//	mockgen -source=internal/repo/contracts.go -destination=internal/usecase/mocks_repo_test.go -package=usecase_test
//

// Package usecase_test is a generated GoMock package.
package usecase_test

import (
	context "context"
	reflect "reflect"
	time "time"

	entity "github.com/evrone/go-clean-template/internal/entity"
	repo "github.com/evrone/go-clean-template/internal/repo"
	gomock "go.uber.org/mock/gomock"
)

// MockTranslationRepo is a mock of TranslationRepo interface.
type MockTranslationRepo struct {
	ctrl     *gomock.Controller
	recorder *MockTranslationRepoMockRecorder
	isgomock struct{}
}

// MockTranslationRepoMockRecorder is the mock recorder for MockTranslationRepo.
type MockTranslationRepoMockRecorder struct {
	mock *MockTranslationRepo
}

// NewMockTranslationRepo creates a new mock instance.
func NewMockTranslationRepo(ctrl *gomock.Controller) *MockTranslationRepo {
	mock := &MockTranslationRepo{ctrl: ctrl}
	mock.recorder = &MockTranslationRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTranslationRepo) EXPECT() *MockTranslationRepoMockRecorder {
	return m.recorder
}

// GetHistory mocks base method.
func (m *MockTranslationRepo) GetHistory(ctx context.Context, userID string) ([]entity.Translation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHistory", ctx, userID)
	ret0, _ := ret[0].([]entity.Translation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHistory indicates an expected call of GetHistory.
func (mr *MockTranslationRepoMockRecorder) GetHistory(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHistory", reflect.TypeOf((*MockTranslationRepo)(nil).GetHistory), ctx, userID)
}

// Store mocks base method.
func (m *MockTranslationRepo) Store(ctx context.Context, userID string, t entity.Translation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, userID, t)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockTranslationRepoMockRecorder) Store(ctx, userID, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockTranslationRepo)(nil).Store), ctx, userID, t)
}

// MockTranslationWebAPI is a mock of TranslationWebAPI interface.
type MockTranslationWebAPI struct {
	ctrl     *gomock.Controller
	recorder *MockTranslationWebAPIMockRecorder
	isgomock struct{}
}

// MockTranslationWebAPIMockRecorder is the mock recorder for MockTranslationWebAPI.
type MockTranslationWebAPIMockRecorder struct {
	mock *MockTranslationWebAPI
}

// NewMockTranslationWebAPI creates a new mock instance.
func NewMockTranslationWebAPI(ctrl *gomock.Controller) *MockTranslationWebAPI {
	mock := &MockTranslationWebAPI{ctrl: ctrl}
	mock.recorder = &MockTranslationWebAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTranslationWebAPI) EXPECT() *MockTranslationWebAPIMockRecorder {
	return m.recorder
}

// Translate mocks base method.
func (m *MockTranslationWebAPI) Translate(ctx context.Context, t entity.Translation) (entity.Translation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Translate", ctx, t)
	ret0, _ := ret[0].(entity.Translation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Translate indicates an expected call of Translate.
func (mr *MockTranslationWebAPIMockRecorder) Translate(ctx, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Translate", reflect.TypeOf((*MockTranslationWebAPI)(nil).Translate), ctx, t)
}

// MockUserRepo is a mock of UserRepo interface.
type MockUserRepo struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepoMockRecorder
	isgomock struct{}
}

// MockUserRepoMockRecorder is the mock recorder for MockUserRepo.
type MockUserRepoMockRecorder struct {
	mock *MockUserRepo
}

// NewMockUserRepo creates a new mock instance.
func NewMockUserRepo(ctrl *gomock.Controller) *MockUserRepo {
	mock := &MockUserRepo{ctrl: ctrl}
	mock.recorder = &MockUserRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepo) EXPECT() *MockUserRepoMockRecorder {
	return m.recorder
}

// GetByEmail mocks base method.
func (m *MockUserRepo) GetByEmail(ctx context.Context, email string) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", ctx, email)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockUserRepoMockRecorder) GetByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockUserRepo)(nil).GetByEmail), ctx, email)
}

// GetByID mocks base method.
func (m *MockUserRepo) GetByID(ctx context.Context, id string) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserRepo)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockUserRepo) List(ctx context.Context, filter repo.UserFilter) ([]entity.User, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter)
	ret0, _ := ret[0].([]entity.User)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockUserRepoMockRecorder) List(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockUserRepo)(nil).List), ctx, filter)
}

// SetStatus mocks base method.
func (m *MockUserRepo) SetStatus(ctx context.Context, id string, status entity.UserStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetStatus indicates an expected call of SetStatus.
func (mr *MockUserRepoMockRecorder) SetStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStatus", reflect.TypeOf((*MockUserRepo)(nil).SetStatus), ctx, id, status)
}

// Store mocks base method.
func (m *MockUserRepo) Store(ctx context.Context, user *entity.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockUserRepoMockRecorder) Store(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockUserRepo)(nil).Store), ctx, user)
}

// Update mocks base method.
func (m *MockUserRepo) Update(ctx context.Context, user *entity.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUserRepoMockRecorder) Update(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserRepo)(nil).Update), ctx, user)
}

// MockRoleRepo is a mock of RoleRepo interface.
type MockRoleRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRoleRepoMockRecorder
	isgomock struct{}
}

// MockRoleRepoMockRecorder is the mock recorder for MockRoleRepo.
type MockRoleRepoMockRecorder struct {
	mock *MockRoleRepo
}

// NewMockRoleRepo creates a new mock instance.
func NewMockRoleRepo(ctrl *gomock.Controller) *MockRoleRepo {
	mock := &MockRoleRepo{ctrl: ctrl}
	mock.recorder = &MockRoleRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoleRepo) EXPECT() *MockRoleRepoMockRecorder {
	return m.recorder
}

// GetByName mocks base method.
func (m *MockRoleRepo) GetByName(ctx context.Context, name entity.RoleName) (entity.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", ctx, name)
	ret0, _ := ret[0].(entity.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockRoleRepoMockRecorder) GetByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockRoleRepo)(nil).GetByName), ctx, name)
}

// List mocks base method.
func (m *MockRoleRepo) List(ctx context.Context) ([]entity.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]entity.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockRoleRepoMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRoleRepo)(nil).List), ctx)
}

// MockTaskRepo is a mock of TaskRepo interface.
type MockTaskRepo struct {
	ctrl     *gomock.Controller
	recorder *MockTaskRepoMockRecorder
	isgomock struct{}
}

// MockTaskRepoMockRecorder is the mock recorder for MockTaskRepo.
type MockTaskRepoMockRecorder struct {
	mock *MockTaskRepo
}

// NewMockTaskRepo creates a new mock instance.
func NewMockTaskRepo(ctrl *gomock.Controller) *MockTaskRepo {
	mock := &MockTaskRepo{ctrl: ctrl}
	mock.recorder = &MockTaskRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskRepo) EXPECT() *MockTaskRepoMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockTaskRepo) Delete(ctx context.Context, userID, taskID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, userID, taskID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTaskRepoMockRecorder) Delete(ctx, userID, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTaskRepo)(nil).Delete), ctx, userID, taskID)
}

// GetByID mocks base method.
func (m *MockTaskRepo) GetByID(ctx context.Context, userID, taskID string) (entity.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, userID, taskID)
	ret0, _ := ret[0].(entity.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTaskRepoMockRecorder) GetByID(ctx, userID, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTaskRepo)(nil).GetByID), ctx, userID, taskID)
}

// List mocks base method.
func (m *MockTaskRepo) List(ctx context.Context, userID string, filter repo.TaskFilter) ([]entity.Task, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, userID, filter)
	ret0, _ := ret[0].([]entity.Task)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockTaskRepoMockRecorder) List(ctx, userID, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTaskRepo)(nil).List), ctx, userID, filter)
}

// Store mocks base method.
func (m *MockTaskRepo) Store(ctx context.Context, task *entity.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockTaskRepoMockRecorder) Store(ctx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockTaskRepo)(nil).Store), ctx, task)
}

// Update mocks base method.
func (m *MockTaskRepo) Update(ctx context.Context, task *entity.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockTaskRepoMockRecorder) Update(ctx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTaskRepo)(nil).Update), ctx, task)
}

// MockCatalogRepo is a mock of CatalogRepo interface.
type MockCatalogRepo struct {
	ctrl     *gomock.Controller
	recorder *MockCatalogRepoMockRecorder
	isgomock struct{}
}

// MockCatalogRepoMockRecorder is the mock recorder for MockCatalogRepo.
type MockCatalogRepoMockRecorder struct {
	mock *MockCatalogRepo
}

// NewMockCatalogRepo creates a new mock instance.
func NewMockCatalogRepo(ctrl *gomock.Controller) *MockCatalogRepo {
	mock := &MockCatalogRepo{ctrl: ctrl}
	mock.recorder = &MockCatalogRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCatalogRepo) EXPECT() *MockCatalogRepoMockRecorder {
	return m.recorder
}

// DeleteProduct mocks base method.
func (m *MockCatalogRepo) DeleteProduct(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProduct", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProduct indicates an expected call of DeleteProduct.
func (mr *MockCatalogRepoMockRecorder) DeleteProduct(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProduct", reflect.TypeOf((*MockCatalogRepo)(nil).DeleteProduct), ctx, id)
}

// GetProduct mocks base method.
func (m *MockCatalogRepo) GetProduct(ctx context.Context, id string) (entity.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProduct", ctx, id)
	ret0, _ := ret[0].(entity.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProduct indicates an expected call of GetProduct.
func (mr *MockCatalogRepoMockRecorder) GetProduct(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProduct", reflect.TypeOf((*MockCatalogRepo)(nil).GetProduct), ctx, id)
}

// ListCategories mocks base method.
func (m *MockCatalogRepo) ListCategories(ctx context.Context) ([]entity.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCategories", ctx)
	ret0, _ := ret[0].([]entity.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCategories indicates an expected call of ListCategories.
func (mr *MockCatalogRepoMockRecorder) ListCategories(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCategories", reflect.TypeOf((*MockCatalogRepo)(nil).ListCategories), ctx)
}

// ListProducts mocks base method.
func (m *MockCatalogRepo) ListProducts(ctx context.Context, filter repo.ProductFilter) ([]entity.Product, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProducts", ctx, filter)
	ret0, _ := ret[0].([]entity.Product)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListProducts indicates an expected call of ListProducts.
func (mr *MockCatalogRepoMockRecorder) ListProducts(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProducts", reflect.TypeOf((*MockCatalogRepo)(nil).ListProducts), ctx, filter)
}

// ListTags mocks base method.
func (m *MockCatalogRepo) ListTags(ctx context.Context) ([]entity.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTags", ctx)
	ret0, _ := ret[0].([]entity.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTags indicates an expected call of ListTags.
func (mr *MockCatalogRepoMockRecorder) ListTags(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTags", reflect.TypeOf((*MockCatalogRepo)(nil).ListTags), ctx)
}

// StoreCategory mocks base method.
func (m *MockCatalogRepo) StoreCategory(ctx context.Context, category *entity.Category) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreCategory", ctx, category)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreCategory indicates an expected call of StoreCategory.
func (mr *MockCatalogRepoMockRecorder) StoreCategory(ctx, category any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreCategory", reflect.TypeOf((*MockCatalogRepo)(nil).StoreCategory), ctx, category)
}

// StoreProduct mocks base method.
func (m *MockCatalogRepo) StoreProduct(ctx context.Context, product *entity.Product) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreProduct", ctx, product)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreProduct indicates an expected call of StoreProduct.
func (mr *MockCatalogRepoMockRecorder) StoreProduct(ctx, product any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreProduct", reflect.TypeOf((*MockCatalogRepo)(nil).StoreProduct), ctx, product)
}

// StoreTag mocks base method.
func (m *MockCatalogRepo) StoreTag(ctx context.Context, tag *entity.Tag) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreTag", ctx, tag)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreTag indicates an expected call of StoreTag.
func (mr *MockCatalogRepoMockRecorder) StoreTag(ctx, tag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreTag", reflect.TypeOf((*MockCatalogRepo)(nil).StoreTag), ctx, tag)
}

// UpdateProduct mocks base method.
func (m *MockCatalogRepo) UpdateProduct(ctx context.Context, product *entity.Product) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProduct", ctx, product)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProduct indicates an expected call of UpdateProduct.
func (mr *MockCatalogRepoMockRecorder) UpdateProduct(ctx, product any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProduct", reflect.TypeOf((*MockCatalogRepo)(nil).UpdateProduct), ctx, product)
}

// MockMediaRepo is a mock of MediaRepo interface.
type MockMediaRepo struct {
	ctrl     *gomock.Controller
	recorder *MockMediaRepoMockRecorder
	isgomock struct{}
}

// MockMediaRepoMockRecorder is the mock recorder for MockMediaRepo.
type MockMediaRepoMockRecorder struct {
	mock *MockMediaRepo
}

// NewMockMediaRepo creates a new mock instance.
func NewMockMediaRepo(ctrl *gomock.Controller) *MockMediaRepo {
	mock := &MockMediaRepo{ctrl: ctrl}
	mock.recorder = &MockMediaRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMediaRepo) EXPECT() *MockMediaRepoMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockMediaRepo) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockMediaRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMediaRepo)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockMediaRepo) Get(ctx context.Context, id string) (entity.MediaAsset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(entity.MediaAsset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockMediaRepoMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockMediaRepo)(nil).Get), ctx, id)
}

// List mocks base method.
func (m *MockMediaRepo) List(ctx context.Context, page entity.Pagination, q string) ([]entity.MediaAsset, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, page, q)
	ret0, _ := ret[0].([]entity.MediaAsset)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockMediaRepoMockRecorder) List(ctx, page, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockMediaRepo)(nil).List), ctx, page, q)
}

// Store mocks base method.
func (m *MockMediaRepo) Store(ctx context.Context, media *entity.MediaAsset) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, media)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockMediaRepoMockRecorder) Store(ctx, media any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockMediaRepo)(nil).Store), ctx, media)
}

// MockSEORepo is a mock of SEORepo interface.
type MockSEORepo struct {
	ctrl     *gomock.Controller
	recorder *MockSEORepoMockRecorder
	isgomock struct{}
}

// MockSEORepoMockRecorder is the mock recorder for MockSEORepo.
type MockSEORepoMockRecorder struct {
	mock *MockSEORepo
}

// NewMockSEORepo creates a new mock instance.
func NewMockSEORepo(ctrl *gomock.Controller) *MockSEORepo {
	mock := &MockSEORepo{ctrl: ctrl}
	mock.recorder = &MockSEORepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSEORepo) EXPECT() *MockSEORepoMockRecorder {
	return m.recorder
}

// GetByOwner mocks base method.
func (m *MockSEORepo) GetByOwner(ctx context.Context, ownerType, ownerID string) (entity.SeoMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByOwner", ctx, ownerType, ownerID)
	ret0, _ := ret[0].(entity.SeoMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByOwner indicates an expected call of GetByOwner.
func (mr *MockSEORepoMockRecorder) GetByOwner(ctx, ownerType, ownerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByOwner", reflect.TypeOf((*MockSEORepo)(nil).GetByOwner), ctx, ownerType, ownerID)
}

// Store mocks base method.
func (m *MockSEORepo) Store(ctx context.Context, meta *entity.SeoMetadata) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, meta)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockSEORepoMockRecorder) Store(ctx, meta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockSEORepo)(nil).Store), ctx, meta)
}

// MockHomepageRepo is a mock of HomepageRepo interface.
type MockHomepageRepo struct {
	ctrl     *gomock.Controller
	recorder *MockHomepageRepoMockRecorder
	isgomock struct{}
}

// MockHomepageRepoMockRecorder is the mock recorder for MockHomepageRepo.
type MockHomepageRepoMockRecorder struct {
	mock *MockHomepageRepo
}

// NewMockHomepageRepo creates a new mock instance.
func NewMockHomepageRepo(ctrl *gomock.Controller) *MockHomepageRepo {
	mock := &MockHomepageRepo{ctrl: ctrl}
	mock.recorder = &MockHomepageRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHomepageRepo) EXPECT() *MockHomepageRepoMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockHomepageRepo) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockHomepageRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockHomepageRepo)(nil).Delete), ctx, id)
}

// List mocks base method.
func (m *MockHomepageRepo) List(ctx context.Context, activeOnly bool) ([]entity.HomepageBlock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, activeOnly)
	ret0, _ := ret[0].([]entity.HomepageBlock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockHomepageRepoMockRecorder) List(ctx, activeOnly any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockHomepageRepo)(nil).List), ctx, activeOnly)
}

// Store mocks base method.
func (m *MockHomepageRepo) Store(ctx context.Context, block *entity.HomepageBlock) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, block)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockHomepageRepoMockRecorder) Store(ctx, block any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockHomepageRepo)(nil).Store), ctx, block)
}

// Update mocks base method.
func (m *MockHomepageRepo) Update(ctx context.Context, block *entity.HomepageBlock) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, block)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockHomepageRepoMockRecorder) Update(ctx, block any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockHomepageRepo)(nil).Update), ctx, block)
}

// MockSupportChannelRepo is a mock of SupportChannelRepo interface.
type MockSupportChannelRepo struct {
	ctrl     *gomock.Controller
	recorder *MockSupportChannelRepoMockRecorder
	isgomock struct{}
}

// MockSupportChannelRepoMockRecorder is the mock recorder for MockSupportChannelRepo.
type MockSupportChannelRepoMockRecorder struct {
	mock *MockSupportChannelRepo
}

// NewMockSupportChannelRepo creates a new mock instance.
func NewMockSupportChannelRepo(ctrl *gomock.Controller) *MockSupportChannelRepo {
	mock := &MockSupportChannelRepo{ctrl: ctrl}
	mock.recorder = &MockSupportChannelRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSupportChannelRepo) EXPECT() *MockSupportChannelRepoMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockSupportChannelRepo) List(ctx context.Context, enabledOnly bool) ([]entity.SupportChannel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, enabledOnly)
	ret0, _ := ret[0].([]entity.SupportChannel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockSupportChannelRepoMockRecorder) List(ctx, enabledOnly any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSupportChannelRepo)(nil).List), ctx, enabledOnly)
}

// Update mocks base method.
func (m *MockSupportChannelRepo) Update(ctx context.Context, channel *entity.SupportChannel) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, channel)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockSupportChannelRepoMockRecorder) Update(ctx, channel any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSupportChannelRepo)(nil).Update), ctx, channel)
}

// MockCartRepo is a mock of CartRepo interface.
type MockCartRepo struct {
	ctrl     *gomock.Controller
	recorder *MockCartRepoMockRecorder
	isgomock struct{}
}

// MockCartRepoMockRecorder is the mock recorder for MockCartRepo.
type MockCartRepoMockRecorder struct {
	mock *MockCartRepo
}

// NewMockCartRepo creates a new mock instance.
func NewMockCartRepo(ctrl *gomock.Controller) *MockCartRepo {
	mock := &MockCartRepo{ctrl: ctrl}
	mock.recorder = &MockCartRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCartRepo) EXPECT() *MockCartRepoMockRecorder {
	return m.recorder
}

// AddItem mocks base method.
func (m *MockCartRepo) AddItem(ctx context.Context, sessionID string, item *entity.CartItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddItem", ctx, sessionID, item)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddItem indicates an expected call of AddItem.
func (mr *MockCartRepoMockRecorder) AddItem(ctx, sessionID, item any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddItem", reflect.TypeOf((*MockCartRepo)(nil).AddItem), ctx, sessionID, item)
}

// Convert mocks base method.
func (m *MockCartRepo) Convert(ctx context.Context, cartID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Convert", ctx, cartID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Convert indicates an expected call of Convert.
func (mr *MockCartRepoMockRecorder) Convert(ctx, cartID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Convert", reflect.TypeOf((*MockCartRepo)(nil).Convert), ctx, cartID)
}

// GetBySession mocks base method.
func (m *MockCartRepo) GetBySession(ctx context.Context, sessionID string) (entity.Cart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySession", ctx, sessionID)
	ret0, _ := ret[0].(entity.Cart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySession indicates an expected call of GetBySession.
func (mr *MockCartRepoMockRecorder) GetBySession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySession", reflect.TypeOf((*MockCartRepo)(nil).GetBySession), ctx, sessionID)
}

// RemoveItem mocks base method.
func (m *MockCartRepo) RemoveItem(ctx context.Context, sessionID, itemID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveItem", ctx, sessionID, itemID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveItem indicates an expected call of RemoveItem.
func (mr *MockCartRepoMockRecorder) RemoveItem(ctx, sessionID, itemID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveItem", reflect.TypeOf((*MockCartRepo)(nil).RemoveItem), ctx, sessionID, itemID)
}

// Store mocks base method.
func (m *MockCartRepo) Store(ctx context.Context, cart *entity.Cart) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, cart)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockCartRepoMockRecorder) Store(ctx, cart any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockCartRepo)(nil).Store), ctx, cart)
}

// UpdateItem mocks base method.
func (m *MockCartRepo) UpdateItem(ctx context.Context, sessionID, itemID string, quantity int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateItem", ctx, sessionID, itemID, quantity)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateItem indicates an expected call of UpdateItem.
func (mr *MockCartRepoMockRecorder) UpdateItem(ctx, sessionID, itemID, quantity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateItem", reflect.TypeOf((*MockCartRepo)(nil).UpdateItem), ctx, sessionID, itemID, quantity)
}

// MockOrderRequestRepo is a mock of OrderRequestRepo interface.
type MockOrderRequestRepo struct {
	ctrl     *gomock.Controller
	recorder *MockOrderRequestRepoMockRecorder
	isgomock struct{}
}

// MockOrderRequestRepoMockRecorder is the mock recorder for MockOrderRequestRepo.
type MockOrderRequestRepoMockRecorder struct {
	mock *MockOrderRequestRepo
}

// NewMockOrderRequestRepo creates a new mock instance.
func NewMockOrderRequestRepo(ctrl *gomock.Controller) *MockOrderRequestRepo {
	mock := &MockOrderRequestRepo{ctrl: ctrl}
	mock.recorder = &MockOrderRequestRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderRequestRepo) EXPECT() *MockOrderRequestRepoMockRecorder {
	return m.recorder
}

// Store mocks base method.
func (m *MockOrderRequestRepo) Store(ctx context.Context, order *entity.OrderRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, order)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockOrderRequestRepoMockRecorder) Store(ctx, order any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockOrderRequestRepo)(nil).Store), ctx, order)
}

// MockLeadRepo is a mock of LeadRepo interface.
type MockLeadRepo struct {
	ctrl     *gomock.Controller
	recorder *MockLeadRepoMockRecorder
	isgomock struct{}
}

// MockLeadRepoMockRecorder is the mock recorder for MockLeadRepo.
type MockLeadRepoMockRecorder struct {
	mock *MockLeadRepo
}

// NewMockLeadRepo creates a new mock instance.
func NewMockLeadRepo(ctrl *gomock.Controller) *MockLeadRepo {
	mock := &MockLeadRepo{ctrl: ctrl}
	mock.recorder = &MockLeadRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLeadRepo) EXPECT() *MockLeadRepoMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockLeadRepo) Get(ctx context.Context, id string) (entity.LeadSubmission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(entity.LeadSubmission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockLeadRepoMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockLeadRepo)(nil).Get), ctx, id)
}

// Store mocks base method.
func (m *MockLeadRepo) Store(ctx context.Context, lead *entity.LeadSubmission) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, lead)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockLeadRepoMockRecorder) Store(ctx, lead any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockLeadRepo)(nil).Store), ctx, lead)
}

// MockContentRepo is a mock of ContentRepo interface.
type MockContentRepo struct {
	ctrl     *gomock.Controller
	recorder *MockContentRepoMockRecorder
	isgomock struct{}
}

// MockContentRepoMockRecorder is the mock recorder for MockContentRepo.
type MockContentRepoMockRecorder struct {
	mock *MockContentRepo
}

// NewMockContentRepo creates a new mock instance.
func NewMockContentRepo(ctrl *gomock.Controller) *MockContentRepo {
	mock := &MockContentRepo{ctrl: ctrl}
	mock.recorder = &MockContentRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContentRepo) EXPECT() *MockContentRepoMockRecorder {
	return m.recorder
}

// DeleteArticle mocks base method.
func (m *MockContentRepo) DeleteArticle(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteArticle", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteArticle indicates an expected call of DeleteArticle.
func (mr *MockContentRepoMockRecorder) DeleteArticle(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteArticle", reflect.TypeOf((*MockContentRepo)(nil).DeleteArticle), ctx, id)
}

// GetArticle mocks base method.
func (m *MockContentRepo) GetArticle(ctx context.Context, idOrSlug string) (entity.ContentArticle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArticle", ctx, idOrSlug)
	ret0, _ := ret[0].(entity.ContentArticle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArticle indicates an expected call of GetArticle.
func (mr *MockContentRepoMockRecorder) GetArticle(ctx, idOrSlug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArticle", reflect.TypeOf((*MockContentRepo)(nil).GetArticle), ctx, idOrSlug)
}

// GetPageBySlug mocks base method.
func (m *MockContentRepo) GetPageBySlug(ctx context.Context, slug string) (entity.StaticPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPageBySlug", ctx, slug)
	ret0, _ := ret[0].(entity.StaticPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPageBySlug indicates an expected call of GetPageBySlug.
func (mr *MockContentRepoMockRecorder) GetPageBySlug(ctx, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPageBySlug", reflect.TypeOf((*MockContentRepo)(nil).GetPageBySlug), ctx, slug)
}

// ListArticles mocks base method.
func (m *MockContentRepo) ListArticles(ctx context.Context, filter entity.ArticleFilter) ([]entity.ContentArticle, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListArticles", ctx, filter)
	ret0, _ := ret[0].([]entity.ContentArticle)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListArticles indicates an expected call of ListArticles.
func (mr *MockContentRepoMockRecorder) ListArticles(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListArticles", reflect.TypeOf((*MockContentRepo)(nil).ListArticles), ctx, filter)
}

// PublishDue mocks base method.
func (m *MockContentRepo) PublishDue(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishDue", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PublishDue indicates an expected call of PublishDue.
func (mr *MockContentRepoMockRecorder) PublishDue(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishDue", reflect.TypeOf((*MockContentRepo)(nil).PublishDue), ctx)
}

// StoreArticle mocks base method.
func (m *MockContentRepo) StoreArticle(ctx context.Context, article *entity.ContentArticle) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreArticle", ctx, article)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreArticle indicates an expected call of StoreArticle.
func (mr *MockContentRepoMockRecorder) StoreArticle(ctx, article any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreArticle", reflect.TypeOf((*MockContentRepo)(nil).StoreArticle), ctx, article)
}

// StorePage mocks base method.
func (m *MockContentRepo) StorePage(ctx context.Context, page *entity.StaticPage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StorePage", ctx, page)
	ret0, _ := ret[0].(error)
	return ret0
}

// StorePage indicates an expected call of StorePage.
func (mr *MockContentRepoMockRecorder) StorePage(ctx, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StorePage", reflect.TypeOf((*MockContentRepo)(nil).StorePage), ctx, page)
}

// UpdateArticle mocks base method.
func (m *MockContentRepo) UpdateArticle(ctx context.Context, article *entity.ContentArticle) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateArticle", ctx, article)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateArticle indicates an expected call of UpdateArticle.
func (mr *MockContentRepoMockRecorder) UpdateArticle(ctx, article any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateArticle", reflect.TypeOf((*MockContentRepo)(nil).UpdateArticle), ctx, article)
}

// UpdatePage mocks base method.
func (m *MockContentRepo) UpdatePage(ctx context.Context, page *entity.StaticPage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePage", ctx, page)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePage indicates an expected call of UpdatePage.
func (mr *MockContentRepoMockRecorder) UpdatePage(ctx, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePage", reflect.TypeOf((*MockContentRepo)(nil).UpdatePage), ctx, page)
}

// MockImportRepo is a mock of ImportRepo interface.
type MockImportRepo struct {
	ctrl     *gomock.Controller
	recorder *MockImportRepoMockRecorder
	isgomock struct{}
}

// MockImportRepoMockRecorder is the mock recorder for MockImportRepo.
type MockImportRepoMockRecorder struct {
	mock *MockImportRepo
}

// NewMockImportRepo creates a new mock instance.
func NewMockImportRepo(ctrl *gomock.Controller) *MockImportRepo {
	mock := &MockImportRepo{ctrl: ctrl}
	mock.recorder = &MockImportRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImportRepo) EXPECT() *MockImportRepoMockRecorder {
	return m.recorder
}

// StoreImportedPost mocks base method.
func (m *MockImportRepo) StoreImportedPost(ctx context.Context, article *entity.ContentArticle) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreImportedPost", ctx, article)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreImportedPost indicates an expected call of StoreImportedPost.
func (mr *MockImportRepoMockRecorder) StoreImportedPost(ctx, article any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreImportedPost", reflect.TypeOf((*MockImportRepo)(nil).StoreImportedPost), ctx, article)
}

// StoreImportedProduct mocks base method.
func (m *MockImportRepo) StoreImportedProduct(ctx context.Context, product *entity.Product) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreImportedProduct", ctx, product)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreImportedProduct indicates an expected call of StoreImportedProduct.
func (mr *MockImportRepoMockRecorder) StoreImportedProduct(ctx, product any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreImportedProduct", reflect.TypeOf((*MockImportRepo)(nil).StoreImportedProduct), ctx, product)
}

// MockAuthRepository is a mock of AuthRepository interface.
type MockAuthRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAuthRepositoryMockRecorder
	isgomock struct{}
}

// MockAuthRepositoryMockRecorder is the mock recorder for MockAuthRepository.
type MockAuthRepositoryMockRecorder struct {
	mock *MockAuthRepository
}

// NewMockAuthRepository creates a new mock instance.
func NewMockAuthRepository(ctrl *gomock.Controller) *MockAuthRepository {
	mock := &MockAuthRepository{ctrl: ctrl}
	mock.recorder = &MockAuthRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthRepository) EXPECT() *MockAuthRepositoryMockRecorder {
	return m.recorder
}

// GetRefreshSession mocks base method.
func (m *MockAuthRepository) GetRefreshSession(ctx context.Context, tokenID string) (entity.RefreshSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRefreshSession", ctx, tokenID)
	ret0, _ := ret[0].(entity.RefreshSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRefreshSession indicates an expected call of GetRefreshSession.
func (mr *MockAuthRepositoryMockRecorder) GetRefreshSession(ctx, tokenID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRefreshSession", reflect.TypeOf((*MockAuthRepository)(nil).GetRefreshSession), ctx, tokenID)
}

// GetUserByEmail mocks base method.
func (m *MockAuthRepository) GetUserByEmail(ctx context.Context, email string) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", ctx, email)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockAuthRepositoryMockRecorder) GetUserByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockAuthRepository)(nil).GetUserByEmail), ctx, email)
}

// GetUserByID mocks base method.
func (m *MockAuthRepository) GetUserByID(ctx context.Context, userID string) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, userID)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockAuthRepositoryMockRecorder) GetUserByID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockAuthRepository)(nil).GetUserByID), ctx, userID)
}

// GetUserByUsername mocks base method.
func (m *MockAuthRepository) GetUserByUsername(ctx context.Context, username string) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByUsername", ctx, username)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByUsername indicates an expected call of GetUserByUsername.
func (mr *MockAuthRepositoryMockRecorder) GetUserByUsername(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByUsername", reflect.TypeOf((*MockAuthRepository)(nil).GetUserByUsername), ctx, username)
}

// RevokeRefreshSession mocks base method.
func (m *MockAuthRepository) RevokeRefreshSession(ctx context.Context, tokenID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeRefreshSession", ctx, tokenID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeRefreshSession indicates an expected call of RevokeRefreshSession.
func (mr *MockAuthRepositoryMockRecorder) RevokeRefreshSession(ctx, tokenID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeRefreshSession", reflect.TypeOf((*MockAuthRepository)(nil).RevokeRefreshSession), ctx, tokenID)
}

// StoreRefreshSession mocks base method.
func (m *MockAuthRepository) StoreRefreshSession(ctx context.Context, session entity.RefreshSession) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreRefreshSession", ctx, session)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreRefreshSession indicates an expected call of StoreRefreshSession.
func (mr *MockAuthRepositoryMockRecorder) StoreRefreshSession(ctx, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreRefreshSession", reflect.TypeOf((*MockAuthRepository)(nil).StoreRefreshSession), ctx, session)
}

// UpsertUser mocks base method.
func (m *MockAuthRepository) UpsertUser(ctx context.Context, user entity.User) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertUser", ctx, user)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertUser indicates an expected call of UpsertUser.
func (mr *MockAuthRepositoryMockRecorder) UpsertUser(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertUser", reflect.TypeOf((*MockAuthRepository)(nil).UpsertUser), ctx, user)
}

// MockCatalogRepository is a mock of CatalogRepository interface.
type MockCatalogRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCatalogRepositoryMockRecorder
	isgomock struct{}
}

// MockCatalogRepositoryMockRecorder is the mock recorder for MockCatalogRepository.
type MockCatalogRepositoryMockRecorder struct {
	mock *MockCatalogRepository
}

// NewMockCatalogRepository creates a new mock instance.
func NewMockCatalogRepository(ctrl *gomock.Controller) *MockCatalogRepository {
	mock := &MockCatalogRepository{ctrl: ctrl}
	mock.recorder = &MockCatalogRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCatalogRepository) EXPECT() *MockCatalogRepositoryMockRecorder {
	return m.recorder
}

// GetSetting mocks base method.
func (m *MockCatalogRepository) GetSetting(ctx context.Context, key string) (entity.Setting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSetting", ctx, key)
	ret0, _ := ret[0].(entity.Setting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSetting indicates an expected call of GetSetting.
func (mr *MockCatalogRepositoryMockRecorder) GetSetting(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSetting", reflect.TypeOf((*MockCatalogRepository)(nil).GetSetting), ctx, key)
}

// GetVisibleProduct mocks base method.
func (m *MockCatalogRepository) GetVisibleProduct(ctx context.Context, actor entity.Actor, productID string) (entity.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVisibleProduct", ctx, actor, productID)
	ret0, _ := ret[0].(entity.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVisibleProduct indicates an expected call of GetVisibleProduct.
func (mr *MockCatalogRepositoryMockRecorder) GetVisibleProduct(ctx, actor, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVisibleProduct", reflect.TypeOf((*MockCatalogRepository)(nil).GetVisibleProduct), ctx, actor, productID)
}

// ListCategories mocks base method.
func (m *MockCatalogRepository) ListCategories(ctx context.Context) ([]entity.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCategories", ctx)
	ret0, _ := ret[0].([]entity.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCategories indicates an expected call of ListCategories.
func (mr *MockCatalogRepositoryMockRecorder) ListCategories(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCategories", reflect.TypeOf((*MockCatalogRepository)(nil).ListCategories), ctx)
}

// ListSettings mocks base method.
func (m *MockCatalogRepository) ListSettings(ctx context.Context) ([]entity.Setting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSettings", ctx)
	ret0, _ := ret[0].([]entity.Setting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSettings indicates an expected call of ListSettings.
func (mr *MockCatalogRepositoryMockRecorder) ListSettings(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSettings", reflect.TypeOf((*MockCatalogRepository)(nil).ListSettings), ctx)
}

// ListVisibleProducts mocks base method.
func (m *MockCatalogRepository) ListVisibleProducts(ctx context.Context, actor entity.Actor, filter repo.ProductFilter) ([]entity.Product, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVisibleProducts", ctx, actor, filter)
	ret0, _ := ret[0].([]entity.Product)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListVisibleProducts indicates an expected call of ListVisibleProducts.
func (mr *MockCatalogRepositoryMockRecorder) ListVisibleProducts(ctx, actor, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVisibleProducts", reflect.TypeOf((*MockCatalogRepository)(nil).ListVisibleProducts), ctx, actor, filter)
}

// MockCheckoutRepository is a mock of CheckoutRepository interface.
type MockCheckoutRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCheckoutRepositoryMockRecorder
	isgomock struct{}
}

// MockCheckoutRepositoryMockRecorder is the mock recorder for MockCheckoutRepository.
type MockCheckoutRepositoryMockRecorder struct {
	mock *MockCheckoutRepository
}

// NewMockCheckoutRepository creates a new mock instance.
func NewMockCheckoutRepository(ctrl *gomock.Controller) *MockCheckoutRepository {
	mock := &MockCheckoutRepository{ctrl: ctrl}
	mock.recorder = &MockCheckoutRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCheckoutRepository) EXPECT() *MockCheckoutRepositoryMockRecorder {
	return m.recorder
}

// AttachPayment mocks base method.
func (m *MockCheckoutRepository) AttachPayment(ctx context.Context, payment entity.Payment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AttachPayment", ctx, payment)
	ret0, _ := ret[0].(error)
	return ret0
}

// AttachPayment indicates an expected call of AttachPayment.
func (mr *MockCheckoutRepositoryMockRecorder) AttachPayment(ctx, payment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttachPayment", reflect.TypeOf((*MockCheckoutRepository)(nil).AttachPayment), ctx, payment)
}

// CreateOrderWithReservation mocks base method.
func (m *MockCheckoutRepository) CreateOrderWithReservation(ctx context.Context, actor entity.Actor, order entity.Order) (entity.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrderWithReservation", ctx, actor, order)
	ret0, _ := ret[0].(entity.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrderWithReservation indicates an expected call of CreateOrderWithReservation.
func (mr *MockCheckoutRepositoryMockRecorder) CreateOrderWithReservation(ctx, actor, order any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrderWithReservation", reflect.TypeOf((*MockCheckoutRepository)(nil).CreateOrderWithReservation), ctx, actor, order)
}

// ReleaseReservation mocks base method.
func (m *MockCheckoutRepository) ReleaseReservation(ctx context.Context, orderID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseReservation", ctx, orderID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReleaseReservation indicates an expected call of ReleaseReservation.
func (mr *MockCheckoutRepositoryMockRecorder) ReleaseReservation(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseReservation", reflect.TypeOf((*MockCheckoutRepository)(nil).ReleaseReservation), ctx, orderID)
}

// UpdateOrderStatus mocks base method.
func (m *MockCheckoutRepository) UpdateOrderStatus(ctx context.Context, orderID string, status entity.OrderStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrderStatus", ctx, orderID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOrderStatus indicates an expected call of UpdateOrderStatus.
func (mr *MockCheckoutRepositoryMockRecorder) UpdateOrderStatus(ctx, orderID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderStatus", reflect.TypeOf((*MockCheckoutRepository)(nil).UpdateOrderStatus), ctx, orderID, status)
}

// MockOrderRepository is a mock of OrderRepository interface.
type MockOrderRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOrderRepositoryMockRecorder
	isgomock struct{}
}

// MockOrderRepositoryMockRecorder is the mock recorder for MockOrderRepository.
type MockOrderRepositoryMockRecorder struct {
	mock *MockOrderRepository
}

// NewMockOrderRepository creates a new mock instance.
func NewMockOrderRepository(ctrl *gomock.Controller) *MockOrderRepository {
	mock := &MockOrderRepository{ctrl: ctrl}
	mock.recorder = &MockOrderRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderRepository) EXPECT() *MockOrderRepositoryMockRecorder {
	return m.recorder
}

// CancelPendingOrder mocks base method.
func (m *MockOrderRepository) CancelPendingOrder(ctx context.Context, actor entity.Actor, orderID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelPendingOrder", ctx, actor, orderID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelPendingOrder indicates an expected call of CancelPendingOrder.
func (mr *MockOrderRepositoryMockRecorder) CancelPendingOrder(ctx, actor, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelPendingOrder", reflect.TypeOf((*MockOrderRepository)(nil).CancelPendingOrder), ctx, actor, orderID)
}

// GetOrderByID mocks base method.
func (m *MockOrderRepository) GetOrderByID(ctx context.Context, orderID string) (entity.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderByID", ctx, orderID)
	ret0, _ := ret[0].(entity.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderByID indicates an expected call of GetOrderByID.
func (mr *MockOrderRepositoryMockRecorder) GetOrderByID(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderByID", reflect.TypeOf((*MockOrderRepository)(nil).GetOrderByID), ctx, orderID)
}

// ListOrdersByOwner mocks base method.
func (m *MockOrderRepository) ListOrdersByOwner(ctx context.Context, userID, email string, page entity.Pagination) ([]entity.Order, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrdersByOwner", ctx, userID, email, page)
	ret0, _ := ret[0].([]entity.Order)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListOrdersByOwner indicates an expected call of ListOrdersByOwner.
func (mr *MockOrderRepositoryMockRecorder) ListOrdersByOwner(ctx, userID, email, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrdersByOwner", reflect.TypeOf((*MockOrderRepository)(nil).ListOrdersByOwner), ctx, userID, email, page)
}

// SubmitRefundRequest mocks base method.
func (m *MockOrderRepository) SubmitRefundRequest(ctx context.Context, refund *entity.RefundRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitRefundRequest", ctx, refund)
	ret0, _ := ret[0].(error)
	return ret0
}

// SubmitRefundRequest indicates an expected call of SubmitRefundRequest.
func (mr *MockOrderRepositoryMockRecorder) SubmitRefundRequest(ctx, refund any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitRefundRequest", reflect.TypeOf((*MockOrderRepository)(nil).SubmitRefundRequest), ctx, refund)
}

// MockProfileRepository is a mock of ProfileRepository interface.
type MockProfileRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProfileRepositoryMockRecorder
	isgomock struct{}
}

// MockProfileRepositoryMockRecorder is the mock recorder for MockProfileRepository.
type MockProfileRepositoryMockRecorder struct {
	mock *MockProfileRepository
}

// NewMockProfileRepository creates a new mock instance.
func NewMockProfileRepository(ctrl *gomock.Controller) *MockProfileRepository {
	mock := &MockProfileRepository{ctrl: ctrl}
	mock.recorder = &MockProfileRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProfileRepository) EXPECT() *MockProfileRepositoryMockRecorder {
	return m.recorder
}

// GetProfile mocks base method.
func (m *MockProfileRepository) GetProfile(ctx context.Context, userID string) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfile", ctx, userID)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProfile indicates an expected call of GetProfile.
func (mr *MockProfileRepositoryMockRecorder) GetProfile(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfile", reflect.TypeOf((*MockProfileRepository)(nil).GetProfile), ctx, userID)
}

// UpdateProfile mocks base method.
func (m *MockProfileRepository) UpdateProfile(ctx context.Context, user entity.User) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProfile", ctx, user)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProfile indicates an expected call of UpdateProfile.
func (mr *MockProfileRepositoryMockRecorder) UpdateProfile(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProfile", reflect.TypeOf((*MockProfileRepository)(nil).UpdateProfile), ctx, user)
}

// MockWishlistRepository is a mock of WishlistRepository interface.
type MockWishlistRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWishlistRepositoryMockRecorder
	isgomock struct{}
}

// MockWishlistRepositoryMockRecorder is the mock recorder for MockWishlistRepository.
type MockWishlistRepositoryMockRecorder struct {
	mock *MockWishlistRepository
}

// NewMockWishlistRepository creates a new mock instance.
func NewMockWishlistRepository(ctrl *gomock.Controller) *MockWishlistRepository {
	mock := &MockWishlistRepository{ctrl: ctrl}
	mock.recorder = &MockWishlistRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWishlistRepository) EXPECT() *MockWishlistRepositoryMockRecorder {
	return m.recorder
}

// DeleteWishlistItem mocks base method.
func (m *MockWishlistRepository) DeleteWishlistItem(ctx context.Context, itemID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWishlistItem", ctx, itemID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWishlistItem indicates an expected call of DeleteWishlistItem.
func (mr *MockWishlistRepositoryMockRecorder) DeleteWishlistItem(ctx, itemID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWishlistItem", reflect.TypeOf((*MockWishlistRepository)(nil).DeleteWishlistItem), ctx, itemID)
}

// ListReviews mocks base method.
func (m *MockWishlistRepository) ListReviews(ctx context.Context, productID string) ([]entity.Review, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListReviews", ctx, productID)
	ret0, _ := ret[0].([]entity.Review)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListReviews indicates an expected call of ListReviews.
func (mr *MockWishlistRepositoryMockRecorder) ListReviews(ctx, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListReviews", reflect.TypeOf((*MockWishlistRepository)(nil).ListReviews), ctx, productID)
}

// ListWishlistItems mocks base method.
func (m *MockWishlistRepository) ListWishlistItems(ctx context.Context, page entity.Pagination) ([]entity.WishlistItem, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWishlistItems", ctx, page)
	ret0, _ := ret[0].([]entity.WishlistItem)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListWishlistItems indicates an expected call of ListWishlistItems.
func (mr *MockWishlistRepositoryMockRecorder) ListWishlistItems(ctx, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWishlistItems", reflect.TypeOf((*MockWishlistRepository)(nil).ListWishlistItems), ctx, page)
}

// StoreReview mocks base method.
func (m *MockWishlistRepository) StoreReview(ctx context.Context, review entity.Review) (entity.Review, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreReview", ctx, review)
	ret0, _ := ret[0].(entity.Review)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StoreReview indicates an expected call of StoreReview.
func (mr *MockWishlistRepositoryMockRecorder) StoreReview(ctx, review any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreReview", reflect.TypeOf((*MockWishlistRepository)(nil).StoreReview), ctx, review)
}

// StoreWishlistItem mocks base method.
func (m *MockWishlistRepository) StoreWishlistItem(ctx context.Context, item entity.WishlistItem) (entity.WishlistItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreWishlistItem", ctx, item)
	ret0, _ := ret[0].(entity.WishlistItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StoreWishlistItem indicates an expected call of StoreWishlistItem.
func (mr *MockWishlistRepositoryMockRecorder) StoreWishlistItem(ctx, item any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreWishlistItem", reflect.TypeOf((*MockWishlistRepository)(nil).StoreWishlistItem), ctx, item)
}

// ToggleWishlistVote mocks base method.
func (m *MockWishlistRepository) ToggleWishlistVote(ctx context.Context, itemID int64, userID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToggleWishlistVote", ctx, itemID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ToggleWishlistVote indicates an expected call of ToggleWishlistVote.
func (mr *MockWishlistRepositoryMockRecorder) ToggleWishlistVote(ctx, itemID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToggleWishlistVote", reflect.TypeOf((*MockWishlistRepository)(nil).ToggleWishlistVote), ctx, itemID, userID)
}

// UpdateWishlistItem mocks base method.
func (m *MockWishlistRepository) UpdateWishlistItem(ctx context.Context, item entity.WishlistItem) (entity.WishlistItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWishlistItem", ctx, item)
	ret0, _ := ret[0].(entity.WishlistItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateWishlistItem indicates an expected call of UpdateWishlistItem.
func (mr *MockWishlistRepositoryMockRecorder) UpdateWishlistItem(ctx, item any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWishlistItem", reflect.TypeOf((*MockWishlistRepository)(nil).UpdateWishlistItem), ctx, item)
}

// MockNotificationRepository is a mock of NotificationRepository interface.
type MockNotificationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationRepositoryMockRecorder
	isgomock struct{}
}

// MockNotificationRepositoryMockRecorder is the mock recorder for MockNotificationRepository.
type MockNotificationRepositoryMockRecorder struct {
	mock *MockNotificationRepository
}

// NewMockNotificationRepository creates a new mock instance.
func NewMockNotificationRepository(ctrl *gomock.Controller) *MockNotificationRepository {
	mock := &MockNotificationRepository{ctrl: ctrl}
	mock.recorder = &MockNotificationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationRepository) EXPECT() *MockNotificationRepositoryMockRecorder {
	return m.recorder
}

// ClearAll mocks base method.
func (m *MockNotificationRepository) ClearAll(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearAll", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearAll indicates an expected call of ClearAll.
func (mr *MockNotificationRepositoryMockRecorder) ClearAll(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearAll", reflect.TypeOf((*MockNotificationRepository)(nil).ClearAll), ctx, userID)
}

// ListBroadcastMessages mocks base method.
func (m *MockNotificationRepository) ListBroadcastMessages(ctx context.Context, page entity.Pagination) ([]entity.BroadcastMessage, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBroadcastMessages", ctx, page)
	ret0, _ := ret[0].([]entity.BroadcastMessage)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListBroadcastMessages indicates an expected call of ListBroadcastMessages.
func (mr *MockNotificationRepositoryMockRecorder) ListBroadcastMessages(ctx, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBroadcastMessages", reflect.TypeOf((*MockNotificationRepository)(nil).ListBroadcastMessages), ctx, page)
}

// ListUserNotifications mocks base method.
func (m *MockNotificationRepository) ListUserNotifications(ctx context.Context, userID string, page entity.Pagination) ([]entity.UserNotification, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUserNotifications", ctx, userID, page)
	ret0, _ := ret[0].([]entity.UserNotification)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListUserNotifications indicates an expected call of ListUserNotifications.
func (mr *MockNotificationRepositoryMockRecorder) ListUserNotifications(ctx, userID, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUserNotifications", reflect.TypeOf((*MockNotificationRepository)(nil).ListUserNotifications), ctx, userID, page)
}

// MarkAllRead mocks base method.
func (m *MockNotificationRepository) MarkAllRead(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAllRead", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAllRead indicates an expected call of MarkAllRead.
func (mr *MockNotificationRepositoryMockRecorder) MarkAllRead(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAllRead", reflect.TypeOf((*MockNotificationRepository)(nil).MarkAllRead), ctx, userID)
}

// MarkNotificationRead mocks base method.
func (m *MockNotificationRepository) MarkNotificationRead(ctx context.Context, userID string, notificationID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkNotificationRead", ctx, userID, notificationID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkNotificationRead indicates an expected call of MarkNotificationRead.
func (mr *MockNotificationRepositoryMockRecorder) MarkNotificationRead(ctx, userID, notificationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkNotificationRead", reflect.TypeOf((*MockNotificationRepository)(nil).MarkNotificationRead), ctx, userID, notificationID)
}

// MockAdminRepository is a mock of AdminRepository interface.
type MockAdminRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAdminRepositoryMockRecorder
	isgomock struct{}
}

// MockAdminRepositoryMockRecorder is the mock recorder for MockAdminRepository.
type MockAdminRepositoryMockRecorder struct {
	mock *MockAdminRepository
}

// NewMockAdminRepository creates a new mock instance.
func NewMockAdminRepository(ctrl *gomock.Controller) *MockAdminRepository {
	mock := &MockAdminRepository{ctrl: ctrl}
	mock.recorder = &MockAdminRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdminRepository) EXPECT() *MockAdminRepositoryMockRecorder {
	return m.recorder
}

// BulkUpdateReviewStatus mocks base method.
func (m *MockAdminRepository) BulkUpdateReviewStatus(ctx context.Context, reviewIDs []int64, status entity.ReviewStatus) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkUpdateReviewStatus", ctx, reviewIDs, status)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkUpdateReviewStatus indicates an expected call of BulkUpdateReviewStatus.
func (mr *MockAdminRepositoryMockRecorder) BulkUpdateReviewStatus(ctx, reviewIDs, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkUpdateReviewStatus", reflect.TypeOf((*MockAdminRepository)(nil).BulkUpdateReviewStatus), ctx, reviewIDs, status)
}

// DeleteOrder mocks base method.
func (m *MockAdminRepository) DeleteOrder(ctx context.Context, orderID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOrder", ctx, orderID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOrder indicates an expected call of DeleteOrder.
func (mr *MockAdminRepositoryMockRecorder) DeleteOrder(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOrder", reflect.TypeOf((*MockAdminRepository)(nil).DeleteOrder), ctx, orderID)
}

// DeleteReview mocks base method.
func (m *MockAdminRepository) DeleteReview(ctx context.Context, reviewID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteReview", ctx, reviewID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteReview indicates an expected call of DeleteReview.
func (mr *MockAdminRepositoryMockRecorder) DeleteReview(ctx, reviewID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteReview", reflect.TypeOf((*MockAdminRepository)(nil).DeleteReview), ctx, reviewID)
}

// DeleteSetting mocks base method.
func (m *MockAdminRepository) DeleteSetting(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSetting", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSetting indicates an expected call of DeleteSetting.
func (mr *MockAdminRepositoryMockRecorder) DeleteSetting(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSetting", reflect.TypeOf((*MockAdminRepository)(nil).DeleteSetting), ctx, key)
}

// GetOrderByID mocks base method.
func (m *MockAdminRepository) GetOrderByID(ctx context.Context, orderID string) (entity.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderByID", ctx, orderID)
	ret0, _ := ret[0].(entity.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderByID indicates an expected call of GetOrderByID.
func (mr *MockAdminRepositoryMockRecorder) GetOrderByID(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderByID", reflect.TypeOf((*MockAdminRepository)(nil).GetOrderByID), ctx, orderID)
}

// GetOrderRefundStatus mocks base method.
func (m *MockAdminRepository) GetOrderRefundStatus(ctx context.Context, orderID string) (entity.RefundRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderRefundStatus", ctx, orderID)
	ret0, _ := ret[0].(entity.RefundRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderRefundStatus indicates an expected call of GetOrderRefundStatus.
func (mr *MockAdminRepositoryMockRecorder) GetOrderRefundStatus(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderRefundStatus", reflect.TypeOf((*MockAdminRepository)(nil).GetOrderRefundStatus), ctx, orderID)
}

// GetRefundRequest mocks base method.
func (m *MockAdminRepository) GetRefundRequest(ctx context.Context, refundID int64) (entity.RefundRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRefundRequest", ctx, refundID)
	ret0, _ := ret[0].(entity.RefundRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRefundRequest indicates an expected call of GetRefundRequest.
func (mr *MockAdminRepositoryMockRecorder) GetRefundRequest(ctx, refundID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRefundRequest", reflect.TypeOf((*MockAdminRepository)(nil).GetRefundRequest), ctx, refundID)
}

// ListAdminMessages mocks base method.
func (m *MockAdminRepository) ListAdminMessages(ctx context.Context) ([]entity.AdminMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAdminMessages", ctx)
	ret0, _ := ret[0].([]entity.AdminMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAdminMessages indicates an expected call of ListAdminMessages.
func (mr *MockAdminRepositoryMockRecorder) ListAdminMessages(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAdminMessages", reflect.TypeOf((*MockAdminRepository)(nil).ListAdminMessages), ctx)
}

// ListOrders mocks base method.
func (m *MockAdminRepository) ListOrders(ctx context.Context, page entity.Pagination, query, status string) ([]entity.Order, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrders", ctx, page, query, status)
	ret0, _ := ret[0].([]entity.Order)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListOrders indicates an expected call of ListOrders.
func (mr *MockAdminRepositoryMockRecorder) ListOrders(ctx, page, query, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrders", reflect.TypeOf((*MockAdminRepository)(nil).ListOrders), ctx, page, query, status)
}

// ListRefundRequests mocks base method.
func (m *MockAdminRepository) ListRefundRequests(ctx context.Context, status string) ([]entity.RefundRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRefundRequests", ctx, status)
	ret0, _ := ret[0].([]entity.RefundRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRefundRequests indicates an expected call of ListRefundRequests.
func (mr *MockAdminRepositoryMockRecorder) ListRefundRequests(ctx, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRefundRequests", reflect.TypeOf((*MockAdminRepository)(nil).ListRefundRequests), ctx, status)
}

// ListReviews mocks base method.
func (m *MockAdminRepository) ListReviews(ctx context.Context, page entity.Pagination, query, status string) ([]entity.Review, repo.ReviewModerationStats, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListReviews", ctx, page, query, status)
	ret0, _ := ret[0].([]entity.Review)
	ret1, _ := ret[1].(repo.ReviewModerationStats)
	ret2, _ := ret[2].(int)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// ListReviews indicates an expected call of ListReviews.
func (mr *MockAdminRepositoryMockRecorder) ListReviews(ctx, page, query, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListReviews", reflect.TypeOf((*MockAdminRepository)(nil).ListReviews), ctx, page, query, status)
}

// ListSettings mocks base method.
func (m *MockAdminRepository) ListSettings(ctx context.Context) ([]entity.Setting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSettings", ctx)
	ret0, _ := ret[0].([]entity.Setting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSettings indicates an expected call of ListSettings.
func (mr *MockAdminRepositoryMockRecorder) ListSettings(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSettings", reflect.TypeOf((*MockAdminRepository)(nil).ListSettings), ctx)
}

// ListUsers mocks base method.
func (m *MockAdminRepository) ListUsers(ctx context.Context, page entity.Pagination) ([]entity.User, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", ctx, page)
	ret0, _ := ret[0].([]entity.User)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockAdminRepositoryMockRecorder) ListUsers(ctx, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockAdminRepository)(nil).ListUsers), ctx, page)
}

// ProcessRefund mocks base method.
func (m *MockAdminRepository) ProcessRefund(ctx context.Context, refundID int64, approve bool, adminUsername, note string) (entity.RefundRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessRefund", ctx, refundID, approve, adminUsername, note)
	ret0, _ := ret[0].(entity.RefundRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessRefund indicates an expected call of ProcessRefund.
func (mr *MockAdminRepositoryMockRecorder) ProcessRefund(ctx, refundID, approve, adminUsername, note any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessRefund", reflect.TypeOf((*MockAdminRepository)(nil).ProcessRefund), ctx, refundID, approve, adminUsername, note)
}

// RebuildProductAggregates mocks base method.
func (m *MockAdminRepository) RebuildProductAggregates(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RebuildProductAggregates", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// RebuildProductAggregates indicates an expected call of RebuildProductAggregates.
func (mr *MockAdminRepositoryMockRecorder) RebuildProductAggregates(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RebuildProductAggregates", reflect.TypeOf((*MockAdminRepository)(nil).RebuildProductAggregates), ctx)
}

// StoreAdminMessage mocks base method.
func (m *MockAdminRepository) StoreAdminMessage(ctx context.Context, msg entity.AdminMessage) (entity.AdminMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreAdminMessage", ctx, msg)
	ret0, _ := ret[0].(entity.AdminMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StoreAdminMessage indicates an expected call of StoreAdminMessage.
func (mr *MockAdminRepositoryMockRecorder) StoreAdminMessage(ctx, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreAdminMessage", reflect.TypeOf((*MockAdminRepository)(nil).StoreAdminMessage), ctx, msg)
}

// StoreSetting mocks base method.
func (m *MockAdminRepository) StoreSetting(ctx context.Context, setting entity.Setting) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreSetting", ctx, setting)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreSetting indicates an expected call of StoreSetting.
func (mr *MockAdminRepositoryMockRecorder) StoreSetting(ctx, setting any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreSetting", reflect.TypeOf((*MockAdminRepository)(nil).StoreSetting), ctx, setting)
}

// UpdateOrderStatus mocks base method.
func (m *MockAdminRepository) UpdateOrderStatus(ctx context.Context, orderID string, status entity.OrderStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrderStatus", ctx, orderID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOrderStatus indicates an expected call of UpdateOrderStatus.
func (mr *MockAdminRepositoryMockRecorder) UpdateOrderStatus(ctx, orderID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderStatus", reflect.TypeOf((*MockAdminRepository)(nil).UpdateOrderStatus), ctx, orderID, status)
}

// UpdateReviewStatus mocks base method.
func (m *MockAdminRepository) UpdateReviewStatus(ctx context.Context, reviewID int64, status entity.ReviewStatus) (entity.Review, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateReviewStatus", ctx, reviewID, status)
	ret0, _ := ret[0].(entity.Review)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateReviewStatus indicates an expected call of UpdateReviewStatus.
func (mr *MockAdminRepositoryMockRecorder) UpdateReviewStatus(ctx, reviewID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateReviewStatus", reflect.TypeOf((*MockAdminRepository)(nil).UpdateReviewStatus), ctx, reviewID, status)
}

// UpdateUserStatus mocks base method.
func (m *MockAdminRepository) UpdateUserStatus(ctx context.Context, userID string, status entity.UserStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserStatus", ctx, userID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserStatus indicates an expected call of UpdateUserStatus.
func (mr *MockAdminRepositoryMockRecorder) UpdateUserStatus(ctx, userID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserStatus", reflect.TypeOf((*MockAdminRepository)(nil).UpdateUserStatus), ctx, userID, status)
}

// MockMaintenanceRepository is a mock of MaintenanceRepository interface.
type MockMaintenanceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMaintenanceRepositoryMockRecorder
	isgomock struct{}
}

// MockMaintenanceRepositoryMockRecorder is the mock recorder for MockMaintenanceRepository.
type MockMaintenanceRepositoryMockRecorder struct {
	mock *MockMaintenanceRepository
}

// NewMockMaintenanceRepository creates a new mock instance.
func NewMockMaintenanceRepository(ctrl *gomock.Controller) *MockMaintenanceRepository {
	mock := &MockMaintenanceRepository{ctrl: ctrl}
	mock.recorder = &MockMaintenanceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMaintenanceRepository) EXPECT() *MockMaintenanceRepositoryMockRecorder {
	return m.recorder
}

// CancelExpiredPendingOrders mocks base method.
func (m *MockMaintenanceRepository) CancelExpiredPendingOrders(ctx context.Context, olderThan time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelExpiredPendingOrders", ctx, olderThan)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelExpiredPendingOrders indicates an expected call of CancelExpiredPendingOrders.
func (mr *MockMaintenanceRepositoryMockRecorder) CancelExpiredPendingOrders(ctx, olderThan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelExpiredPendingOrders", reflect.TypeOf((*MockMaintenanceRepository)(nil).CancelExpiredPendingOrders), ctx, olderThan)
}

// SyncProductAggregates mocks base method.
func (m *MockMaintenanceRepository) SyncProductAggregates(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncProductAggregates", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// SyncProductAggregates indicates an expected call of SyncProductAggregates.
func (mr *MockMaintenanceRepositoryMockRecorder) SyncProductAggregates(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncProductAggregates", reflect.TypeOf((*MockMaintenanceRepository)(nil).SyncProductAggregates), ctx)
}
