// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/usecase/contracts.go
//
// Generated by this command:
//
//	mockgen -source ./internal/usecase/contracts.go -package usecase_test
//

// Package usecase_test is a generated GoMock package.
package usecase_test

import (
	context "context"
	reflect "reflect"

	entity "github.com/evrone/go-clean-template/internal/entity"
	usecase "github.com/evrone/go-clean-template/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockTranslation is a mock of Translation interface.
type MockTranslation struct {
	ctrl     *gomock.Controller
	recorder *MockTranslationMockRecorder
	isgomock struct{}
}

// MockTranslationMockRecorder is the mock recorder for MockTranslation.
type MockTranslationMockRecorder struct {
	mock *MockTranslation
}

// NewMockTranslation creates a new mock instance.
func NewMockTranslation(ctrl *gomock.Controller) *MockTranslation {
	mock := &MockTranslation{ctrl: ctrl}
	mock.recorder = &MockTranslationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTranslation) EXPECT() *MockTranslationMockRecorder {
	return m.recorder
}

// History mocks base method.
func (m *MockTranslation) History(ctx context.Context, userID string) (entity.TranslationHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "History", ctx, userID)
	ret0, _ := ret[0].(entity.TranslationHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// History indicates an expected call of History.
func (mr *MockTranslationMockRecorder) History(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "History", reflect.TypeOf((*MockTranslation)(nil).History), ctx, userID)
}

// Translate mocks base method.
func (m *MockTranslation) Translate(ctx context.Context, userID string, t entity.Translation) (entity.Translation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Translate", ctx, userID, t)
	ret0, _ := ret[0].(entity.Translation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Translate indicates an expected call of Translate.
func (mr *MockTranslationMockRecorder) Translate(ctx, userID, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Translate", reflect.TypeOf((*MockTranslation)(nil).Translate), ctx, userID, t)
}

// MockUser is a mock of User interface.
type MockUser struct {
	ctrl     *gomock.Controller
	recorder *MockUserMockRecorder
	isgomock struct{}
}

// MockUserMockRecorder is the mock recorder for MockUser.
type MockUserMockRecorder struct {
	mock *MockUser
}

// NewMockUser creates a new mock instance.
func NewMockUser(ctrl *gomock.Controller) *MockUser {
	mock := &MockUser{ctrl: ctrl}
	mock.recorder = &MockUserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUser) EXPECT() *MockUserMockRecorder {
	return m.recorder
}

// CreateAdminUser mocks base method.
func (m *MockUser) CreateAdminUser(ctx context.Context, actorID, username, email, password string, role entity.RoleName) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAdminUser", ctx, actorID, username, email, password, role)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAdminUser indicates an expected call of CreateAdminUser.
func (mr *MockUserMockRecorder) CreateAdminUser(ctx, actorID, username, email, password, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAdminUser", reflect.TypeOf((*MockUser)(nil).CreateAdminUser), ctx, actorID, username, email, password, role)
}

// GetUser mocks base method.
func (m *MockUser) GetUser(ctx context.Context, userID string) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, userID)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockUserMockRecorder) GetUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockUser)(nil).GetUser), ctx, userID)
}

// List mocks base method.
func (m *MockUser) List(ctx context.Context, limit, offset int) ([]entity.User, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, limit, offset)
	ret0, _ := ret[0].([]entity.User)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockUserMockRecorder) List(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockUser)(nil).List), ctx, limit, offset)
}

// Lock mocks base method.
func (m *MockUser) Lock(ctx context.Context, actorID, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Lock", ctx, actorID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Lock indicates an expected call of Lock.
func (mr *MockUserMockRecorder) Lock(ctx, actorID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lock", reflect.TypeOf((*MockUser)(nil).Lock), ctx, actorID, userID)
}

// Login mocks base method.
func (m *MockUser) Login(ctx context.Context, email, password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, email, password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockUserMockRecorder) Login(ctx, email, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockUser)(nil).Login), ctx, email, password)
}

// Register mocks base method.
func (m *MockUser) Register(ctx context.Context, username, email, password string) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, username, email, password)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockUserMockRecorder) Register(ctx, username, email, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockUser)(nil).Register), ctx, username, email, password)
}

// Unlock mocks base method.
func (m *MockUser) Unlock(ctx context.Context, actorID, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unlock", ctx, actorID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unlock indicates an expected call of Unlock.
func (mr *MockUserMockRecorder) Unlock(ctx, actorID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unlock", reflect.TypeOf((*MockUser)(nil).Unlock), ctx, actorID, userID)
}

// UpdateProfile mocks base method.
func (m *MockUser) UpdateProfile(ctx context.Context, userID, displayName string) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProfile", ctx, userID, displayName)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProfile indicates an expected call of UpdateProfile.
func (mr *MockUserMockRecorder) UpdateProfile(ctx, userID, displayName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProfile", reflect.TypeOf((*MockUser)(nil).UpdateProfile), ctx, userID, displayName)
}

// MockTask is a mock of Task interface.
type MockTask struct {
	ctrl     *gomock.Controller
	recorder *MockTaskMockRecorder
	isgomock struct{}
}

// MockTaskMockRecorder is the mock recorder for MockTask.
type MockTaskMockRecorder struct {
	mock *MockTask
}

// NewMockTask creates a new mock instance.
func NewMockTask(ctrl *gomock.Controller) *MockTask {
	mock := &MockTask{ctrl: ctrl}
	mock.recorder = &MockTaskMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTask) EXPECT() *MockTaskMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTask) Create(ctx context.Context, userID, title, description string) (entity.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, userID, title, description)
	ret0, _ := ret[0].(entity.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTaskMockRecorder) Create(ctx, userID, title, description any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTask)(nil).Create), ctx, userID, title, description)
}

// Delete mocks base method.
func (m *MockTask) Delete(ctx context.Context, userID, taskID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, userID, taskID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTaskMockRecorder) Delete(ctx, userID, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTask)(nil).Delete), ctx, userID, taskID)
}

// Get mocks base method.
func (m *MockTask) Get(ctx context.Context, userID, taskID string) (entity.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, userID, taskID)
	ret0, _ := ret[0].(entity.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockTaskMockRecorder) Get(ctx, userID, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTask)(nil).Get), ctx, userID, taskID)
}

// List mocks base method.
func (m *MockTask) List(ctx context.Context, userID string, status *entity.TaskStatus, limit, offset int) ([]entity.Task, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, userID, status, limit, offset)
	ret0, _ := ret[0].([]entity.Task)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockTaskMockRecorder) List(ctx, userID, status, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTask)(nil).List), ctx, userID, status, limit, offset)
}

// Transition mocks base method.
func (m *MockTask) Transition(ctx context.Context, userID, taskID string, newStatus entity.TaskStatus) (entity.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transition", ctx, userID, taskID, newStatus)
	ret0, _ := ret[0].(entity.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Transition indicates an expected call of Transition.
func (mr *MockTaskMockRecorder) Transition(ctx, userID, taskID, newStatus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transition", reflect.TypeOf((*MockTask)(nil).Transition), ctx, userID, taskID, newStatus)
}

// Update mocks base method.
func (m *MockTask) Update(ctx context.Context, userID, taskID, title, description string) (entity.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, userID, taskID, title, description)
	ret0, _ := ret[0].(entity.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockTaskMockRecorder) Update(ctx, userID, taskID, title, description any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTask)(nil).Update), ctx, userID, taskID, title, description)
}

// MockCatalog is a mock of Catalog interface.
type MockCatalog struct {
	ctrl     *gomock.Controller
	recorder *MockCatalogMockRecorder
	isgomock struct{}
}

// MockCatalogMockRecorder is the mock recorder for MockCatalog.
type MockCatalogMockRecorder struct {
	mock *MockCatalog
}

// NewMockCatalog creates a new mock instance.
func NewMockCatalog(ctrl *gomock.Controller) *MockCatalog {
	mock := &MockCatalog{ctrl: ctrl}
	mock.recorder = &MockCatalogMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCatalog) EXPECT() *MockCatalogMockRecorder {
	return m.recorder
}

// CreateCategory mocks base method.
func (m *MockCatalog) CreateCategory(ctx context.Context, category entity.Category) (entity.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCategory", ctx, category)
	ret0, _ := ret[0].(entity.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCategory indicates an expected call of CreateCategory.
func (mr *MockCatalogMockRecorder) CreateCategory(ctx, category any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCategory", reflect.TypeOf((*MockCatalog)(nil).CreateCategory), ctx, category)
}

// CreateProduct mocks base method.
func (m *MockCatalog) CreateProduct(ctx context.Context, product entity.Product) (entity.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProduct", ctx, product)
	ret0, _ := ret[0].(entity.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProduct indicates an expected call of CreateProduct.
func (mr *MockCatalogMockRecorder) CreateProduct(ctx, product any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProduct", reflect.TypeOf((*MockCatalog)(nil).CreateProduct), ctx, product)
}

// CreateTag mocks base method.
func (m *MockCatalog) CreateTag(ctx context.Context, tag entity.Tag) (entity.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTag", ctx, tag)
	ret0, _ := ret[0].(entity.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTag indicates an expected call of CreateTag.
func (mr *MockCatalogMockRecorder) CreateTag(ctx, tag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTag", reflect.TypeOf((*MockCatalog)(nil).CreateTag), ctx, tag)
}

// DeleteProduct mocks base method.
func (m *MockCatalog) DeleteProduct(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProduct", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProduct indicates an expected call of DeleteProduct.
func (mr *MockCatalogMockRecorder) DeleteProduct(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProduct", reflect.TypeOf((*MockCatalog)(nil).DeleteProduct), ctx, id)
}

// GetProduct mocks base method.
func (m *MockCatalog) GetProduct(ctx context.Context, id string) (entity.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProduct", ctx, id)
	ret0, _ := ret[0].(entity.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProduct indicates an expected call of GetProduct.
func (mr *MockCatalogMockRecorder) GetProduct(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProduct", reflect.TypeOf((*MockCatalog)(nil).GetProduct), ctx, id)
}

// ListCategories mocks base method.
func (m *MockCatalog) ListCategories(ctx context.Context) ([]entity.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCategories", ctx)
	ret0, _ := ret[0].([]entity.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCategories indicates an expected call of ListCategories.
func (mr *MockCatalogMockRecorder) ListCategories(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCategories", reflect.TypeOf((*MockCatalog)(nil).ListCategories), ctx)
}

// ListProducts mocks base method.
func (m *MockCatalog) ListProducts(ctx context.Context, filter entity.ProductFilter) ([]entity.Product, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProducts", ctx, filter)
	ret0, _ := ret[0].([]entity.Product)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListProducts indicates an expected call of ListProducts.
func (mr *MockCatalogMockRecorder) ListProducts(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProducts", reflect.TypeOf((*MockCatalog)(nil).ListProducts), ctx, filter)
}

// ListTags mocks base method.
func (m *MockCatalog) ListTags(ctx context.Context) ([]entity.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTags", ctx)
	ret0, _ := ret[0].([]entity.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTags indicates an expected call of ListTags.
func (mr *MockCatalogMockRecorder) ListTags(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTags", reflect.TypeOf((*MockCatalog)(nil).ListTags), ctx)
}

// UpdateProduct mocks base method.
func (m *MockCatalog) UpdateProduct(ctx context.Context, product entity.Product) (entity.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProduct", ctx, product)
	ret0, _ := ret[0].(entity.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProduct indicates an expected call of UpdateProduct.
func (mr *MockCatalogMockRecorder) UpdateProduct(ctx, product any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProduct", reflect.TypeOf((*MockCatalog)(nil).UpdateProduct), ctx, product)
}

// MockMedia is a mock of Media interface.
type MockMedia struct {
	ctrl     *gomock.Controller
	recorder *MockMediaMockRecorder
	isgomock struct{}
}

// MockMediaMockRecorder is the mock recorder for MockMedia.
type MockMediaMockRecorder struct {
	mock *MockMedia
}

// NewMockMedia creates a new mock instance.
func NewMockMedia(ctrl *gomock.Controller) *MockMedia {
	mock := &MockMedia{ctrl: ctrl}
	mock.recorder = &MockMediaMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMedia) EXPECT() *MockMediaMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockMedia) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockMediaMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMedia)(nil).Delete), ctx, id)
}

// GeneratePresignedURL mocks base method.
func (m *MockMedia) GeneratePresignedURL(ctx context.Context, fileName, contentType string) (string, string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GeneratePresignedURL", ctx, fileName, contentType)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(string)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GeneratePresignedURL indicates an expected call of GeneratePresignedURL.
func (mr *MockMediaMockRecorder) GeneratePresignedURL(ctx, fileName, contentType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GeneratePresignedURL", reflect.TypeOf((*MockMedia)(nil).GeneratePresignedURL), ctx, fileName, contentType)
}

// List mocks base method.
func (m *MockMedia) List(ctx context.Context, page entity.Pagination, q string) ([]entity.MediaAsset, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, page, q)
	ret0, _ := ret[0].([]entity.MediaAsset)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockMediaMockRecorder) List(ctx, page, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockMedia)(nil).List), ctx, page, q)
}

// Store mocks base method.
func (m *MockMedia) Store(ctx context.Context, media entity.MediaAsset) (entity.MediaAsset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, media)
	ret0, _ := ret[0].(entity.MediaAsset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Store indicates an expected call of Store.
func (mr *MockMediaMockRecorder) Store(ctx, media any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockMedia)(nil).Store), ctx, media)
}

// MockMediaStorage is a mock of MediaStorage interface.
type MockMediaStorage struct {
	ctrl     *gomock.Controller
	recorder *MockMediaStorageMockRecorder
	isgomock struct{}
}

// MockMediaStorageMockRecorder is the mock recorder for MockMediaStorage.
type MockMediaStorageMockRecorder struct {
	mock *MockMediaStorage
}

// NewMockMediaStorage creates a new mock instance.
func NewMockMediaStorage(ctrl *gomock.Controller) *MockMediaStorage {
	mock := &MockMediaStorage{ctrl: ctrl}
	mock.recorder = &MockMediaStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMediaStorage) EXPECT() *MockMediaStorageMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockMediaStorage) Delete(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockMediaStorageMockRecorder) Delete(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMediaStorage)(nil).Delete), ctx, key)
}

// GeneratePresignedURL mocks base method.
func (m *MockMediaStorage) GeneratePresignedURL(ctx context.Context, fileName, contentType string) (string, string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GeneratePresignedURL", ctx, fileName, contentType)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(string)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GeneratePresignedURL indicates an expected call of GeneratePresignedURL.
func (mr *MockMediaStorageMockRecorder) GeneratePresignedURL(ctx, fileName, contentType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GeneratePresignedURL", reflect.TypeOf((*MockMediaStorage)(nil).GeneratePresignedURL), ctx, fileName, contentType)
}

// MockHomepage is a mock of Homepage interface.
type MockHomepage struct {
	ctrl     *gomock.Controller
	recorder *MockHomepageMockRecorder
	isgomock struct{}
}

// MockHomepageMockRecorder is the mock recorder for MockHomepage.
type MockHomepageMockRecorder struct {
	mock *MockHomepage
}

// NewMockHomepage creates a new mock instance.
func NewMockHomepage(ctrl *gomock.Controller) *MockHomepage {
	mock := &MockHomepage{ctrl: ctrl}
	mock.recorder = &MockHomepageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHomepage) EXPECT() *MockHomepageMockRecorder {
	return m.recorder
}

// DeleteBlock mocks base method.
func (m *MockHomepage) DeleteBlock(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBlock", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBlock indicates an expected call of DeleteBlock.
func (mr *MockHomepageMockRecorder) DeleteBlock(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBlock", reflect.TypeOf((*MockHomepage)(nil).DeleteBlock), ctx, id)
}

// ListBlocks mocks base method.
func (m *MockHomepage) ListBlocks(ctx context.Context, activeOnly bool) ([]entity.HomepageBlock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBlocks", ctx, activeOnly)
	ret0, _ := ret[0].([]entity.HomepageBlock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBlocks indicates an expected call of ListBlocks.
func (mr *MockHomepageMockRecorder) ListBlocks(ctx, activeOnly any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBlocks", reflect.TypeOf((*MockHomepage)(nil).ListBlocks), ctx, activeOnly)
}

// ListSupport mocks base method.
func (m *MockHomepage) ListSupport(ctx context.Context, enabledOnly bool) ([]entity.SupportChannel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSupport", ctx, enabledOnly)
	ret0, _ := ret[0].([]entity.SupportChannel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSupport indicates an expected call of ListSupport.
func (mr *MockHomepageMockRecorder) ListSupport(ctx, enabledOnly any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSupport", reflect.TypeOf((*MockHomepage)(nil).ListSupport), ctx, enabledOnly)
}

// StoreBlock mocks base method.
func (m *MockHomepage) StoreBlock(ctx context.Context, block entity.HomepageBlock) (entity.HomepageBlock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreBlock", ctx, block)
	ret0, _ := ret[0].(entity.HomepageBlock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StoreBlock indicates an expected call of StoreBlock.
func (mr *MockHomepageMockRecorder) StoreBlock(ctx, block any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreBlock", reflect.TypeOf((*MockHomepage)(nil).StoreBlock), ctx, block)
}

// UpdateBlock mocks base method.
func (m *MockHomepage) UpdateBlock(ctx context.Context, block entity.HomepageBlock) (entity.HomepageBlock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBlock", ctx, block)
	ret0, _ := ret[0].(entity.HomepageBlock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBlock indicates an expected call of UpdateBlock.
func (mr *MockHomepageMockRecorder) UpdateBlock(ctx, block any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBlock", reflect.TypeOf((*MockHomepage)(nil).UpdateBlock), ctx, block)
}

// UpdateSupport mocks base method.
func (m *MockHomepage) UpdateSupport(ctx context.Context, channel entity.SupportChannel) (entity.SupportChannel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSupport", ctx, channel)
	ret0, _ := ret[0].(entity.SupportChannel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSupport indicates an expected call of UpdateSupport.
func (mr *MockHomepageMockRecorder) UpdateSupport(ctx, channel any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSupport", reflect.TypeOf((*MockHomepage)(nil).UpdateSupport), ctx, channel)
}

// MockCart is a mock of Cart interface.
type MockCart struct {
	ctrl     *gomock.Controller
	recorder *MockCartMockRecorder
	isgomock struct{}
}

// MockCartMockRecorder is the mock recorder for MockCart.
type MockCartMockRecorder struct {
	mock *MockCart
}

// NewMockCart creates a new mock instance.
func NewMockCart(ctrl *gomock.Controller) *MockCart {
	mock := &MockCart{ctrl: ctrl}
	mock.recorder = &MockCartMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCart) EXPECT() *MockCartMockRecorder {
	return m.recorder
}

// AddItem mocks base method.
func (m *MockCart) AddItem(ctx context.Context, sessionID, productID string, quantity int) (entity.Cart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddItem", ctx, sessionID, productID, quantity)
	ret0, _ := ret[0].(entity.Cart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddItem indicates an expected call of AddItem.
func (mr *MockCartMockRecorder) AddItem(ctx, sessionID, productID, quantity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddItem", reflect.TypeOf((*MockCart)(nil).AddItem), ctx, sessionID, productID, quantity)
}

// Create mocks base method.
func (m *MockCart) Create(ctx context.Context, sessionID string) (entity.Cart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, sessionID)
	ret0, _ := ret[0].(entity.Cart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCartMockRecorder) Create(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCart)(nil).Create), ctx, sessionID)
}

// Get mocks base method.
func (m *MockCart) Get(ctx context.Context, sessionID string) (entity.Cart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, sessionID)
	ret0, _ := ret[0].(entity.Cart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCartMockRecorder) Get(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCart)(nil).Get), ctx, sessionID)
}

// RemoveItem mocks base method.
func (m *MockCart) RemoveItem(ctx context.Context, sessionID, itemID string) (entity.Cart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveItem", ctx, sessionID, itemID)
	ret0, _ := ret[0].(entity.Cart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveItem indicates an expected call of RemoveItem.
func (mr *MockCartMockRecorder) RemoveItem(ctx, sessionID, itemID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveItem", reflect.TypeOf((*MockCart)(nil).RemoveItem), ctx, sessionID, itemID)
}

// SubmitOrder mocks base method.
func (m *MockCart) SubmitOrder(ctx context.Context, order entity.OrderRequest) (entity.OrderRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitOrder", ctx, order)
	ret0, _ := ret[0].(entity.OrderRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubmitOrder indicates an expected call of SubmitOrder.
func (mr *MockCartMockRecorder) SubmitOrder(ctx, order any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitOrder", reflect.TypeOf((*MockCart)(nil).SubmitOrder), ctx, order)
}

// UpdateItem mocks base method.
func (m *MockCart) UpdateItem(ctx context.Context, sessionID, itemID string, quantity int) (entity.Cart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateItem", ctx, sessionID, itemID, quantity)
	ret0, _ := ret[0].(entity.Cart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateItem indicates an expected call of UpdateItem.
func (mr *MockCartMockRecorder) UpdateItem(ctx, sessionID, itemID, quantity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateItem", reflect.TypeOf((*MockCart)(nil).UpdateItem), ctx, sessionID, itemID, quantity)
}

// MockLead is a mock of Lead interface.
type MockLead struct {
	ctrl     *gomock.Controller
	recorder *MockLeadMockRecorder
	isgomock struct{}
}

// MockLeadMockRecorder is the mock recorder for MockLead.
type MockLeadMockRecorder struct {
	mock *MockLead
}

// NewMockLead creates a new mock instance.
func NewMockLead(ctrl *gomock.Controller) *MockLead {
	mock := &MockLead{ctrl: ctrl}
	mock.recorder = &MockLeadMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLead) EXPECT() *MockLeadMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockLead) Get(ctx context.Context, id string) (entity.LeadSubmission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(entity.LeadSubmission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockLeadMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockLead)(nil).Get), ctx, id)
}

// Submit mocks base method.
func (m *MockLead) Submit(ctx context.Context, lead entity.LeadSubmission) (entity.LeadSubmission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Submit", ctx, lead)
	ret0, _ := ret[0].(entity.LeadSubmission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Submit indicates an expected call of Submit.
func (mr *MockLeadMockRecorder) Submit(ctx, lead any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Submit", reflect.TypeOf((*MockLead)(nil).Submit), ctx, lead)
}

// MockContent is a mock of Content interface.
type MockContent struct {
	ctrl     *gomock.Controller
	recorder *MockContentMockRecorder
	isgomock struct{}
}

// MockContentMockRecorder is the mock recorder for MockContent.
type MockContentMockRecorder struct {
	mock *MockContent
}

// NewMockContent creates a new mock instance.
func NewMockContent(ctrl *gomock.Controller) *MockContent {
	mock := &MockContent{ctrl: ctrl}
	mock.recorder = &MockContentMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContent) EXPECT() *MockContentMockRecorder {
	return m.recorder
}

// CreateArticle mocks base method.
func (m *MockContent) CreateArticle(ctx context.Context, article entity.ContentArticle) (entity.ContentArticle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateArticle", ctx, article)
	ret0, _ := ret[0].(entity.ContentArticle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateArticle indicates an expected call of CreateArticle.
func (mr *MockContentMockRecorder) CreateArticle(ctx, article any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateArticle", reflect.TypeOf((*MockContent)(nil).CreateArticle), ctx, article)
}

// CreatePage mocks base method.
func (m *MockContent) CreatePage(ctx context.Context, page entity.StaticPage) (entity.StaticPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePage", ctx, page)
	ret0, _ := ret[0].(entity.StaticPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePage indicates an expected call of CreatePage.
func (mr *MockContentMockRecorder) CreatePage(ctx, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePage", reflect.TypeOf((*MockContent)(nil).CreatePage), ctx, page)
}

// DeleteArticle mocks base method.
func (m *MockContent) DeleteArticle(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteArticle", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteArticle indicates an expected call of DeleteArticle.
func (mr *MockContentMockRecorder) DeleteArticle(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteArticle", reflect.TypeOf((*MockContent)(nil).DeleteArticle), ctx, id)
}

// GetArticle mocks base method.
func (m *MockContent) GetArticle(ctx context.Context, idOrSlug string) (entity.ContentArticle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArticle", ctx, idOrSlug)
	ret0, _ := ret[0].(entity.ContentArticle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArticle indicates an expected call of GetArticle.
func (mr *MockContentMockRecorder) GetArticle(ctx, idOrSlug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArticle", reflect.TypeOf((*MockContent)(nil).GetArticle), ctx, idOrSlug)
}

// GetPage mocks base method.
func (m *MockContent) GetPage(ctx context.Context, slug string) (entity.StaticPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPage", ctx, slug)
	ret0, _ := ret[0].(entity.StaticPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPage indicates an expected call of GetPage.
func (mr *MockContentMockRecorder) GetPage(ctx, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPage", reflect.TypeOf((*MockContent)(nil).GetPage), ctx, slug)
}

// ListArticles mocks base method.
func (m *MockContent) ListArticles(ctx context.Context, filter entity.ArticleFilter) ([]entity.ContentArticle, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListArticles", ctx, filter)
	ret0, _ := ret[0].([]entity.ContentArticle)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListArticles indicates an expected call of ListArticles.
func (mr *MockContentMockRecorder) ListArticles(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListArticles", reflect.TypeOf((*MockContent)(nil).ListArticles), ctx, filter)
}

// PublishDue mocks base method.
func (m *MockContent) PublishDue(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishDue", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PublishDue indicates an expected call of PublishDue.
func (mr *MockContentMockRecorder) PublishDue(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishDue", reflect.TypeOf((*MockContent)(nil).PublishDue), ctx)
}

// UpdateArticle mocks base method.
func (m *MockContent) UpdateArticle(ctx context.Context, article entity.ContentArticle) (entity.ContentArticle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateArticle", ctx, article)
	ret0, _ := ret[0].(entity.ContentArticle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateArticle indicates an expected call of UpdateArticle.
func (mr *MockContentMockRecorder) UpdateArticle(ctx, article any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateArticle", reflect.TypeOf((*MockContent)(nil).UpdateArticle), ctx, article)
}

// UpdatePage mocks base method.
func (m *MockContent) UpdatePage(ctx context.Context, page entity.StaticPage) (entity.StaticPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePage", ctx, page)
	ret0, _ := ret[0].(entity.StaticPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePage indicates an expected call of UpdatePage.
func (mr *MockContentMockRecorder) UpdatePage(ctx, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePage", reflect.TypeOf((*MockContent)(nil).UpdatePage), ctx, page)
}

// MockNotification is a mock of Notification interface.
type MockNotification struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationMockRecorder
	isgomock struct{}
}

// MockNotificationMockRecorder is the mock recorder for MockNotification.
type MockNotificationMockRecorder struct {
	mock *MockNotification
}

// NewMockNotification creates a new mock instance.
func NewMockNotification(ctrl *gomock.Controller) *MockNotification {
	mock := &MockNotification{ctrl: ctrl}
	mock.recorder = &MockNotificationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotification) EXPECT() *MockNotificationMockRecorder {
	return m.recorder
}

// Dispatch mocks base method.
func (m *MockNotification) Dispatch(ctx context.Context, notification entity.Notification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Dispatch", ctx, notification)
	ret0, _ := ret[0].(error)
	return ret0
}

// Dispatch indicates an expected call of Dispatch.
func (mr *MockNotificationMockRecorder) Dispatch(ctx, notification any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dispatch", reflect.TypeOf((*MockNotification)(nil).Dispatch), ctx, notification)
}

// MockImporter is a mock of Importer interface.
type MockImporter struct {
	ctrl     *gomock.Controller
	recorder *MockImporterMockRecorder
	isgomock struct{}
}

// MockImporterMockRecorder is the mock recorder for MockImporter.
type MockImporterMockRecorder struct {
	mock *MockImporter
}

// NewMockImporter creates a new mock instance.
func NewMockImporter(ctrl *gomock.Controller) *MockImporter {
	mock := &MockImporter{ctrl: ctrl}
	mock.recorder = &MockImporterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImporter) EXPECT() *MockImporterMockRecorder {
	return m.recorder
}

// Import mocks base method.
func (m *MockImporter) Import(ctx context.Context, items []entity.ImportItem) (entity.ImportResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Import", ctx, items)
	ret0, _ := ret[0].(entity.ImportResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Import indicates an expected call of Import.
func (mr *MockImporterMockRecorder) Import(ctx, items any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Import", reflect.TypeOf((*MockImporter)(nil).Import), ctx, items)
}

// MockAuth is a mock of Auth interface.
type MockAuth struct {
	ctrl     *gomock.Controller
	recorder *MockAuthMockRecorder
	isgomock struct{}
}

// MockAuthMockRecorder is the mock recorder for MockAuth.
type MockAuthMockRecorder struct {
	mock *MockAuth
}

// NewMockAuth creates a new mock instance.
func NewMockAuth(ctrl *gomock.Controller) *MockAuth {
	mock := &MockAuth{ctrl: ctrl}
	mock.recorder = &MockAuthMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuth) EXPECT() *MockAuthMockRecorder {
	return m.recorder
}

// Login mocks base method.
func (m *MockAuth) Login(ctx context.Context, email, password string) (entity.User, string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, email, password)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(string)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// Login indicates an expected call of Login.
func (mr *MockAuthMockRecorder) Login(ctx, email, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockAuth)(nil).Login), ctx, email, password)
}

// Logout mocks base method.
func (m *MockAuth) Logout(ctx context.Context, actor entity.Actor, refreshToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", ctx, actor, refreshToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockAuthMockRecorder) Logout(ctx, actor, refreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockAuth)(nil).Logout), ctx, actor, refreshToken)
}

// Me mocks base method.
func (m *MockAuth) Me(ctx context.Context, actor entity.Actor) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Me", ctx, actor)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Me indicates an expected call of Me.
func (mr *MockAuthMockRecorder) Me(ctx, actor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Me", reflect.TypeOf((*MockAuth)(nil).Me), ctx, actor)
}

// Refresh mocks base method.
func (m *MockAuth) Refresh(ctx context.Context, refreshToken string) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Refresh", ctx, refreshToken)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Refresh indicates an expected call of Refresh.
func (mr *MockAuthMockRecorder) Refresh(ctx, refreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refresh", reflect.TypeOf((*MockAuth)(nil).Refresh), ctx, refreshToken)
}

// MockCheckout is a mock of Checkout interface.
type MockCheckout struct {
	ctrl     *gomock.Controller
	recorder *MockCheckoutMockRecorder
	isgomock struct{}
}

// MockCheckoutMockRecorder is the mock recorder for MockCheckout.
type MockCheckoutMockRecorder struct {
	mock *MockCheckout
}

// NewMockCheckout creates a new mock instance.
func NewMockCheckout(ctrl *gomock.Controller) *MockCheckout {
	mock := &MockCheckout{ctrl: ctrl}
	mock.recorder = &MockCheckoutMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCheckout) EXPECT() *MockCheckoutMockRecorder {
	return m.recorder
}

// Cancel mocks base method.
func (m *MockCheckout) Cancel(ctx context.Context, actor entity.Actor, orderID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cancel", ctx, actor, orderID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Cancel indicates an expected call of Cancel.
func (mr *MockCheckoutMockRecorder) Cancel(ctx, actor, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cancel", reflect.TypeOf((*MockCheckout)(nil).Cancel), ctx, actor, orderID)
}

// CreateOrder mocks base method.
func (m *MockCheckout) CreateOrder(ctx context.Context, actor entity.Actor, productID string, quantity int, email string, usePoints bool) (entity.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrder", ctx, actor, productID, quantity, email, usePoints)
	ret0, _ := ret[0].(entity.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrder indicates an expected call of CreateOrder.
func (mr *MockCheckoutMockRecorder) CreateOrder(ctx, actor, productID, quantity, email, usePoints any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrder", reflect.TypeOf((*MockCheckout)(nil).CreateOrder), ctx, actor, productID, quantity, email, usePoints)
}

// PaymentNotify mocks base method.
func (m *MockCheckout) PaymentNotify(ctx context.Context, payload map[string]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PaymentNotify", ctx, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// PaymentNotify indicates an expected call of PaymentNotify.
func (mr *MockCheckoutMockRecorder) PaymentNotify(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PaymentNotify", reflect.TypeOf((*MockCheckout)(nil).PaymentNotify), ctx, payload)
}

// PaymentParams mocks base method.
func (m *MockCheckout) PaymentParams(ctx context.Context, actor entity.Actor, orderID string) (usecase.PaymentParams, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PaymentParams", ctx, actor, orderID)
	ret0, _ := ret[0].(usecase.PaymentParams)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PaymentParams indicates an expected call of PaymentParams.
func (mr *MockCheckoutMockRecorder) PaymentParams(ctx, actor, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PaymentParams", reflect.TypeOf((*MockCheckout)(nil).PaymentParams), ctx, actor, orderID)
}

// PaymentStatus mocks base method.
func (m *MockCheckout) PaymentStatus(ctx context.Context, orderID string) (entity.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PaymentStatus", ctx, orderID)
	ret0, _ := ret[0].(entity.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PaymentStatus indicates an expected call of PaymentStatus.
func (mr *MockCheckoutMockRecorder) PaymentStatus(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PaymentStatus", reflect.TypeOf((*MockCheckout)(nil).PaymentStatus), ctx, orderID)
}

// Preview mocks base method.
func (m *MockCheckout) Preview(ctx context.Context, actor entity.Actor, productID string, quantity int, usePoints bool) (usecase.AmountBreakdown, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Preview", ctx, actor, productID, quantity, usePoints)
	ret0, _ := ret[0].(usecase.AmountBreakdown)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Preview indicates an expected call of Preview.
func (mr *MockCheckoutMockRecorder) Preview(ctx, actor, productID, quantity, usePoints any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Preview", reflect.TypeOf((*MockCheckout)(nil).Preview), ctx, actor, productID, quantity, usePoints)
}

// MockOrders is a mock of Orders interface.
type MockOrders struct {
	ctrl     *gomock.Controller
	recorder *MockOrdersMockRecorder
	isgomock struct{}
}

// MockOrdersMockRecorder is the mock recorder for MockOrders.
type MockOrdersMockRecorder struct {
	mock *MockOrders
}

// NewMockOrders creates a new mock instance.
func NewMockOrders(ctrl *gomock.Controller) *MockOrders {
	mock := &MockOrders{ctrl: ctrl}
	mock.recorder = &MockOrdersMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrders) EXPECT() *MockOrdersMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockOrders) Get(ctx context.Context, actor entity.Actor, orderID string) (entity.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, actor, orderID)
	ret0, _ := ret[0].(entity.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockOrdersMockRecorder) Get(ctx, actor, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockOrders)(nil).Get), ctx, actor, orderID)
}

// List mocks base method.
func (m *MockOrders) List(ctx context.Context, actor entity.Actor, email string, page entity.Pagination) ([]entity.Order, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, actor, email, page)
	ret0, _ := ret[0].([]entity.Order)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockOrdersMockRecorder) List(ctx, actor, email, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockOrders)(nil).List), ctx, actor, email, page)
}

// RequestRefund mocks base method.
func (m *MockOrders) RequestRefund(ctx context.Context, actor entity.Actor, orderID, reason string) (entity.RefundRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestRefund", ctx, actor, orderID, reason)
	ret0, _ := ret[0].(entity.RefundRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RequestRefund indicates an expected call of RequestRefund.
func (mr *MockOrdersMockRecorder) RequestRefund(ctx, actor, orderID, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestRefund", reflect.TypeOf((*MockOrders)(nil).RequestRefund), ctx, actor, orderID, reason)
}

// MockProfile is a mock of Profile interface.
type MockProfile struct {
	ctrl     *gomock.Controller
	recorder *MockProfileMockRecorder
	isgomock struct{}
}

// MockProfileMockRecorder is the mock recorder for MockProfile.
type MockProfileMockRecorder struct {
	mock *MockProfile
}

// NewMockProfile creates a new mock instance.
func NewMockProfile(ctrl *gomock.Controller) *MockProfile {
	mock := &MockProfile{ctrl: ctrl}
	mock.recorder = &MockProfileMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProfile) EXPECT() *MockProfileMockRecorder {
	return m.recorder
}

// Checkin mocks base method.
func (m *MockProfile) Checkin(ctx context.Context, actor entity.Actor) (entity.DailyCheckin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Checkin", ctx, actor)
	ret0, _ := ret[0].(entity.DailyCheckin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Checkin indicates an expected call of Checkin.
func (mr *MockProfileMockRecorder) Checkin(ctx, actor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Checkin", reflect.TypeOf((*MockProfile)(nil).Checkin), ctx, actor)
}

// Get mocks base method.
func (m *MockProfile) Get(ctx context.Context, actor entity.Actor) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, actor)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockProfileMockRecorder) Get(ctx, actor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockProfile)(nil).Get), ctx, actor)
}

// Update mocks base method.
func (m *MockProfile) Update(ctx context.Context, actor entity.Actor, email string, desktopNotificationsEnabled bool) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, actor, email, desktopNotificationsEnabled)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockProfileMockRecorder) Update(ctx, actor, email, desktopNotificationsEnabled any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockProfile)(nil).Update), ctx, actor, email, desktopNotificationsEnabled)
}

// MockWishlist is a mock of Wishlist interface.
type MockWishlist struct {
	ctrl     *gomock.Controller
	recorder *MockWishlistMockRecorder
	isgomock struct{}
}

// MockWishlistMockRecorder is the mock recorder for MockWishlist.
type MockWishlistMockRecorder struct {
	mock *MockWishlist
}

// NewMockWishlist creates a new mock instance.
func NewMockWishlist(ctrl *gomock.Controller) *MockWishlist {
	mock := &MockWishlist{ctrl: ctrl}
	mock.recorder = &MockWishlistMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWishlist) EXPECT() *MockWishlistMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockWishlist) Create(ctx context.Context, actor entity.Actor, title, description string) (entity.WishlistItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, actor, title, description)
	ret0, _ := ret[0].(entity.WishlistItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockWishlistMockRecorder) Create(ctx, actor, title, description any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockWishlist)(nil).Create), ctx, actor, title, description)
}

// CreateReview mocks base method.
func (m *MockWishlist) CreateReview(ctx context.Context, actor entity.Actor, review entity.Review) (entity.Review, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateReview", ctx, actor, review)
	ret0, _ := ret[0].(entity.Review)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateReview indicates an expected call of CreateReview.
func (mr *MockWishlistMockRecorder) CreateReview(ctx, actor, review any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateReview", reflect.TypeOf((*MockWishlist)(nil).CreateReview), ctx, actor, review)
}

// Delete mocks base method.
func (m *MockWishlist) Delete(ctx context.Context, actor entity.Actor, itemID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, actor, itemID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockWishlistMockRecorder) Delete(ctx, actor, itemID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockWishlist)(nil).Delete), ctx, actor, itemID)
}

// List mocks base method.
func (m *MockWishlist) List(ctx context.Context, page entity.Pagination) ([]entity.WishlistItem, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, page)
	ret0, _ := ret[0].([]entity.WishlistItem)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockWishlistMockRecorder) List(ctx, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockWishlist)(nil).List), ctx, page)
}

// ListReviews mocks base method.
func (m *MockWishlist) ListReviews(ctx context.Context, productID string) ([]entity.Review, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListReviews", ctx, productID)
	ret0, _ := ret[0].([]entity.Review)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListReviews indicates an expected call of ListReviews.
func (mr *MockWishlistMockRecorder) ListReviews(ctx, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListReviews", reflect.TypeOf((*MockWishlist)(nil).ListReviews), ctx, productID)
}

// ToggleVote mocks base method.
func (m *MockWishlist) ToggleVote(ctx context.Context, actor entity.Actor, itemID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToggleVote", ctx, actor, itemID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ToggleVote indicates an expected call of ToggleVote.
func (mr *MockWishlistMockRecorder) ToggleVote(ctx, actor, itemID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToggleVote", reflect.TypeOf((*MockWishlist)(nil).ToggleVote), ctx, actor, itemID)
}

// Update mocks base method.
func (m *MockWishlist) Update(ctx context.Context, actor entity.Actor, item entity.WishlistItem) (entity.WishlistItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, actor, item)
	ret0, _ := ret[0].(entity.WishlistItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockWishlistMockRecorder) Update(ctx, actor, item any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockWishlist)(nil).Update), ctx, actor, item)
}

// MockNotificationCenter is a mock of NotificationCenter interface.
type MockNotificationCenter struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationCenterMockRecorder
	isgomock struct{}
}

// MockNotificationCenterMockRecorder is the mock recorder for MockNotificationCenter.
type MockNotificationCenterMockRecorder struct {
	mock *MockNotificationCenter
}

// NewMockNotificationCenter creates a new mock instance.
func NewMockNotificationCenter(ctrl *gomock.Controller) *MockNotificationCenter {
	mock := &MockNotificationCenter{ctrl: ctrl}
	mock.recorder = &MockNotificationCenterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationCenter) EXPECT() *MockNotificationCenterMockRecorder {
	return m.recorder
}

// Clear mocks base method.
func (m *MockNotificationCenter) Clear(ctx context.Context, actor entity.Actor) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Clear", ctx, actor)
	ret0, _ := ret[0].(error)
	return ret0
}

// Clear indicates an expected call of Clear.
func (mr *MockNotificationCenterMockRecorder) Clear(ctx, actor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clear", reflect.TypeOf((*MockNotificationCenter)(nil).Clear), ctx, actor)
}

// Inbox mocks base method.
func (m *MockNotificationCenter) Inbox(ctx context.Context, actor entity.Actor, page entity.Pagination) ([]entity.UserNotification, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Inbox", ctx, actor, page)
	ret0, _ := ret[0].([]entity.UserNotification)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Inbox indicates an expected call of Inbox.
func (mr *MockNotificationCenterMockRecorder) Inbox(ctx, actor, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Inbox", reflect.TypeOf((*MockNotificationCenter)(nil).Inbox), ctx, actor, page)
}

// MarkAllRead mocks base method.
func (m *MockNotificationCenter) MarkAllRead(ctx context.Context, actor entity.Actor) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAllRead", ctx, actor)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAllRead indicates an expected call of MarkAllRead.
func (mr *MockNotificationCenterMockRecorder) MarkAllRead(ctx, actor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAllRead", reflect.TypeOf((*MockNotificationCenter)(nil).MarkAllRead), ctx, actor)
}

// MarkRead mocks base method.
func (m *MockNotificationCenter) MarkRead(ctx context.Context, actor entity.Actor, notificationID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkRead", ctx, actor, notificationID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkRead indicates an expected call of MarkRead.
func (mr *MockNotificationCenterMockRecorder) MarkRead(ctx, actor, notificationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkRead", reflect.TypeOf((*MockNotificationCenter)(nil).MarkRead), ctx, actor, notificationID)
}

// UnreadCount mocks base method.
func (m *MockNotificationCenter) UnreadCount(ctx context.Context, actor entity.Actor) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnreadCount", ctx, actor)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnreadCount indicates an expected call of UnreadCount.
func (mr *MockNotificationCenterMockRecorder) UnreadCount(ctx, actor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnreadCount", reflect.TypeOf((*MockNotificationCenter)(nil).UnreadCount), ctx, actor)
}

// MockAdmin is a mock of Admin interface.
type MockAdmin struct {
	ctrl     *gomock.Controller
	recorder *MockAdminMockRecorder
	isgomock struct{}
}

// MockAdminMockRecorder is the mock recorder for MockAdmin.
type MockAdminMockRecorder struct {
	mock *MockAdmin
}

// NewMockAdmin creates a new mock instance.
func NewMockAdmin(ctrl *gomock.Controller) *MockAdmin {
	mock := &MockAdmin{ctrl: ctrl}
	mock.recorder = &MockAdminMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdmin) EXPECT() *MockAdminMockRecorder {
	return m.recorder
}

// GetOrder mocks base method.
func (m *MockAdmin) GetOrder(ctx context.Context, actor entity.Actor, orderID string) (entity.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrder", ctx, actor, orderID)
	ret0, _ := ret[0].(entity.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrder indicates an expected call of GetOrder.
func (mr *MockAdminMockRecorder) GetOrder(ctx, actor, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrder", reflect.TypeOf((*MockAdmin)(nil).GetOrder), ctx, actor, orderID)
}

// ListOrders mocks base method.
func (m *MockAdmin) ListOrders(ctx context.Context, actor entity.Actor, page entity.Pagination, query, status string) ([]entity.Order, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrders", ctx, actor, page, query, status)
	ret0, _ := ret[0].([]entity.Order)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListOrders indicates an expected call of ListOrders.
func (mr *MockAdminMockRecorder) ListOrders(ctx, actor, page, query, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrders", reflect.TypeOf((*MockAdmin)(nil).ListOrders), ctx, actor, page, query, status)
}

// ListUsers mocks base method.
func (m *MockAdmin) ListUsers(ctx context.Context, actor entity.Actor, page entity.Pagination) ([]entity.User, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", ctx, actor, page)
	ret0, _ := ret[0].([]entity.User)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockAdminMockRecorder) ListUsers(ctx, actor, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockAdmin)(nil).ListUsers), ctx, actor, page)
}

// RepairAggregates mocks base method.
func (m *MockAdmin) RepairAggregates(ctx context.Context, actor entity.Actor) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RepairAggregates", ctx, actor)
	ret0, _ := ret[0].(error)
	return ret0
}

// RepairAggregates indicates an expected call of RepairAggregates.
func (mr *MockAdminMockRecorder) RepairAggregates(ctx, actor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RepairAggregates", reflect.TypeOf((*MockAdmin)(nil).RepairAggregates), ctx, actor)
}

// UpdateUserPoints mocks base method.
func (m *MockAdmin) UpdateUserPoints(ctx context.Context, actor entity.Actor, userID string, points int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserPoints", ctx, actor, userID, points)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserPoints indicates an expected call of UpdateUserPoints.
func (mr *MockAdminMockRecorder) UpdateUserPoints(ctx, actor, userID, points any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserPoints", reflect.TypeOf((*MockAdmin)(nil).UpdateUserPoints), ctx, actor, userID, points)
}

// UpdateUserStatus mocks base method.
func (m *MockAdmin) UpdateUserStatus(ctx context.Context, actor entity.Actor, userID string, status entity.UserStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserStatus", ctx, actor, userID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserStatus indicates an expected call of UpdateUserStatus.
func (mr *MockAdminMockRecorder) UpdateUserStatus(ctx, actor, userID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserStatus", reflect.TypeOf((*MockAdmin)(nil).UpdateUserStatus), ctx, actor, userID, status)
}

// MockMaintenance is a mock of Maintenance interface.
type MockMaintenance struct {
	ctrl     *gomock.Controller
	recorder *MockMaintenanceMockRecorder
	isgomock struct{}
}

// MockMaintenanceMockRecorder is the mock recorder for MockMaintenance.
type MockMaintenanceMockRecorder struct {
	mock *MockMaintenance
}

// NewMockMaintenance creates a new mock instance.
func NewMockMaintenance(ctrl *gomock.Controller) *MockMaintenance {
	mock := &MockMaintenance{ctrl: ctrl}
	mock.recorder = &MockMaintenanceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMaintenance) EXPECT() *MockMaintenanceMockRecorder {
	return m.recorder
}

// CancelExpiredPendingOrders mocks base method.
func (m *MockMaintenance) CancelExpiredPendingOrders(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelExpiredPendingOrders", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelExpiredPendingOrders indicates an expected call of CancelExpiredPendingOrders.
func (mr *MockMaintenanceMockRecorder) CancelExpiredPendingOrders(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelExpiredPendingOrders", reflect.TypeOf((*MockMaintenance)(nil).CancelExpiredPendingOrders), ctx)
}

// SyncProductAggregates mocks base method.
func (m *MockMaintenance) SyncProductAggregates(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncProductAggregates", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// SyncProductAggregates indicates an expected call of SyncProductAggregates.
func (mr *MockMaintenanceMockRecorder) SyncProductAggregates(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncProductAggregates", reflect.TypeOf((*MockMaintenance)(nil).SyncProductAggregates), ctx)
}
